.yaspeller.json
=> Правит наращение числительных

people/ezhkov/index.md, people/nlopin/index.md, people/pepelsbey/index.md, people/solarrust/index.md
Переносит папку Люди [из репозитория платформы](https://github.com/Y-Doka/platform) в контентный.
=> Добавляет папку people

people/akellbl4/index.md
=> Добавляет akellbl4 в people

css/articles/animation/index.md
=> Добавляет в статью по анимациям тег спринта 2

html/doka/dl-dd-dt/demos/dl-dd-dt.html, html/doka/dl-dd-dt/index.md, html/doka/footer/demos/footer.html, html/doka/footer/index.md
Ишью [616](https://github.com/Y-Doka/y-doka.site/issues/616) в Y-Doka / y-doka.site
=> Добавляет демо для статей footer и dl-dd-dt

css/articles/flexbox-guide/index.md
=> Правит путь до обложки

CODEOWNERS
Кажется, мы забыли добавить @tachisis в качестве редактора к главному ридми-файлу
=> Добавляет редактора в ридми

css/doka/font-family/demos/index.html, css/doka/font-family/index.md, css/doka/placeholder/demos/index.html, css/doka/placeholder/index.md
Добавляет демо к статьям:
- font-family [(#244)](https://github.com/Y-Doka/y-doka.site/issues/244)
- ::placeholder
=> Добавляет демо к двум статьям

css/doka/calc/demos/fit.html, css/doka/calc/demos/nonfit.html, css/doka/calc/index.md, css/doka/calc/practice/solarrust.md
Закрывает [#235](https://github.com/Y-Doka/y-doka.site/issues/235)
=> Добавляет демо в статью calc()

.github/workflows/surge-preview.yml
Попробовал исправить [проблему](https://github.com/Y-Doka/platform/issues/159).
=> Добавляет условия для превью при пиаре

.github/workflows/editorconfig.yml, .github/workflows/yaspeller.yml
Ускорил yaspeller. Пытался ускорить editorconfig, но он только все файлы может проверять. С другой стороны, он итак быстро работает. Можно попробовать сделать проверку с помощью вариант не на JS, но такое предлагать я не решусь :)
@pepelsbey @nlopin @solarrust @furtivite
=> Оптимизация тестов

.gitignore
У нас нет ни dist, ни node_modules
=> Удаляет ненужные игноры

html/doka/form/demos/email.html, html/doka/form/demos/forms.html, html/doka/form/index.md
- Убирает обёртку `article__code`
- Убирает борьбу с автозаполнением `internal-autofill-selected`
- Упрощает демку последовательно на тегах
- Упрощает подмену радиокнопок
- Форматирует примеры в статье
Сделал в рамках #776
=> Рефакторит демку с формами

html/doka/video/demos/background.html, html/doka/video/demos/formats.html, html/doka/video/demos/poster.html, html/doka/video/index.md
- Убирает обёртку `article__code`
- Упрощает демку последовательно на тегах
- Форматирует примеры в статье
Сделал в рамках #776
=> Рефакторит демки по видео

js/doka/element-keydown-keyup/demos/keydown.html, js/doka/element-keydown-keyup/demos/keyup.html, js/doka/element-keydown-keyup/index.md
@ValyaBro я переделала эти демки с тех пор, как ты их видела последний раз :)
https://codepen.io/y-doka/pen/YzNrGve
https://codepen.io/y-doka/pen/GRrMjGB
=> Добавляет демо в статью Element.Keydown/Keyup

.github/workflows/netlify-deploy.yml, README.md
Это позволит показывать, в каком статусе наши тесты, что-то вроде такого:
Каждый бейдж — ссылка на соответствующий список экшенов, где можно узнать подробности.
=> Добавляет бейджи в ридми

.github/workflows/netlify-deploy.yml, .github/workflows/sort-dictionary.yml, .github/workflows/surge-preview.yml, .github/workflows/yaspeller-pr.yml
Меняет пути в связи с изменением названия организации.
[Ишью #178](https://github.com/Y-Doka/platform/issues/178)
=> Изменения в экшенах

css/required/index.md
Обратите внимание, плз: в примере и в демке код какой-то не по бэму, но у нас не формулированы правила по коду и я сама не стала лезть.
=> Правит статью про required

html/br-pros-cons/index.md
Имя автора должно быть в списке, иначе не выводится
=> Правит имя автора

.github/scripts/update-index.js, .github/workflows/updated-at-field.yml
PR связан с [задачей вывода даты последнего редактирования статьи](https://github.com/doka-guide/platform/issues/232)
[PR для платформы](https://github.com/doka-guide/platform/pull/239)
=> Добавляет action для создания/обновления data-файлов с статей

.github/workflows/updated-at-field.yml
Надо было изменить поле file_pattern на ./**/index.11tydata.json
=> Правит `file_pattern ` в action'е обновления полей

CODEOWNERS
=> Добавляет @bespoyasov в CODEOWNERS

.github/workflows/yaspeller-all.yml, .github/workflows/yaspeller-pr.yml
Проблема решена. Теперь всё будет работать корректно!
=> Пробует распознать проблемы с экшенами

.github/scripts/update-index.js
=> Добавляет пустую строку в data-файл для соответствия editorconfig

tools/index.md
Можно всё выбросить и оставить только структуру :)
=>  Добавляет черновик индекса инструментов

people/tachisis/index.md
@tachisis норм или другую ссылку? :)
=> Добавляет профиль редактору

html/picture/index.md
=> Правит мету в статье про <picture>

html/br-pros-cons/index.md
=> Правит мету в статье про <br>

.github/workflows/link-all.yml, .github/workflows/link-pr.yml
Возникла [ошибка](https://github.com/doka-guide/content/actions/runs/1104114907) при проверке ссылок.
Дополнил триггер — улучшение)
=> Исправляет работу экшена и дополняет триггер

js/architecture-mvc/index.md
Обнаружилась проблема со сборкой сайта. Она возникала из-за дублирующихся тегов в статье.
=> Исправляет дублирующиеся поля в мете

.github/scripts/frontmatter.js, .github/workflows/frontmatter-lint.yml, .github/workflows/frontmatter.yml
Реализован функционал автоматической проверки и правки меты в материалах.
В PR мета проверяется на наличие обязательных полей.
В `main` перепроверяется наличие обязательных полей и производится автоматическая сортировка. Если встречаются поля, которые не могут быть в мете, выдаётся ошибка.
=> Добавляет правку меты

docs/demos.md
Так аккуратнее, чтобы был правильный пример.
=> Выравнивает атрибуты в демке

.github/workflows/surge-preview.yml
Возникла необходимость изменить бизнес-логику размещения комментариев о превью сайта в PR.
=> Меняет способ комментирования превью в PR

js/index.md
Забыл, что теперь вместе с самой статьей надо добавлять её в индекс
=> Добавляет статьи в индекс JS

js/deal-with-forms/demos/mars-form/index.html, js/deal-with-forms/index.md
- Перевёл демку про полёт на Марс на русский, чтобы она была понятна всем
- Применил стиль кода для HTML: свернул теги обратно, убрал camelCase из атрибутов
- Применил стиль кода для JS: одиночные кавычки, точки с запятой
- Добавил атрибут `sandbox` на фрейм, чтобы автофокус не прокручивал статью к фрейму
=> Рефакторит демку про формы

js/number-tostring/index.md, js/object-tostring/index.md, js/parseint/index.md
@nlopin, кажется, я забыл несколько бэктиков поставить. Сорри.
=> Добавляет забытые бэктики

people/igorkamyshev/index.md, people/igsekor/index.md, people/windrushfarer/index.md
Fixes #1582
Ошибка оказалась не в платформе, а контенте.
=> Правит ссылку на Твиттер

css/custom-properties/index.md, css/linear-gradient/index.md, css/numeric-types/index.md, css/radial-gradient/index.md, html/br/index.md, html/flow/index.md, js/array-find/index.md, js/cleartimeout/index.md, js/element-textcontent/index.md, js/errors/index.md, js/settimeout/index.md, people/lenaryan/index.md, people/nionka/index.md, people/realetive/index.md, people/vladimir/index.md, tools/xml/index.md, tools/yaml/index.md
Наши авторы достойны личных страничек и имён. Добавляет.
=> Создаёт странички людям в папке people

css/index.md
=> Убирает дублирование статьи в индексе

html/index.md
@pepelsbey @tachisis аналогично, приглашают внимательно посмотреть на индекс HTML
=> Добавляет в индекс HTML беспризорные статьи, меняет порядок

js/array-every/index.md
Полагаю, что здесь опечатка и вместо some должен быть every.
=> Заменяет some на every

js/array-some/index.md
У нас был неверный код в примере, если попробовать его выполнить, то произойдёт ошибка
=> Правит стиль кода и ошибку с двумя const в array.some

js/infinite-scroll/index.md
В статье "Подгрузка контента при прокрутке" исправляет неверное присваивание значения переменной "nextPage"
=> Исправляет переменную в примере кода

css/box-shadow/demos/pixelart/index.html
=> Центрирует пиксельную демку

.github/workflows/pr-checks.yml, .github/workflows/pr-labels.yml
Исправляет ошибку #2202 при формировании лейблов для PR.
=> Меняет флоу автоматизации для PR

.github/workflows/editorconfig.yml, .github/workflows/frontmatter-lint.yml, .github/workflows/maintainer-helper.yml, .github/workflows/pr-checks.yml, .github/workflows/pr-labels.yml, .github/workflows/sort-dictionary.yml, .github/workflows/surge-preview.yml, .github/workflows/update-dates.yml, .github/workflows/update-index.yml, .github/workflows/yaspeller-all.yml
[По примеру платформы](https://github.com/doka-guide/platform/pull/690)
=> Обновляет Node.js в экшенах

.github/workflows/product-deploy.yml
Переделывает деплой. Теперь всё уходит на свой сервер
=> Реализация деплоя

css/index.md
Добавляет статьи в индекс CSS, подраздел «Колонки»:
- `column-rule`
- `column-rule-color`
- `column-rule-style`
- `column-rule-width`
=> Добавляет новые статьи в индекс CSS

CHANGELOG.md
Чую будут ещё, так что пока черновик.
=> Обновляет список новинок

.github/workflows/product-deploy.yml, README.md
=> Отпиливает всё про Netlify

.github/scripts/labeler.js, .github/workflows/pr-labels.yml, .labeler.json
Возникли проблемы с этим скриптом. Вопросы решены по большей части. Предлагаю посмотреть на работу экшена в будущем.
=> Вносит номинальные правки в PR Labeler

css/lang/demos/q/index.html, css/lang/index.md
Для немецких существительных критично важно наличие артикля, плюс они всегда пишутся с заглавной буквы.
=> Вносит лингвистические правки

css/combined-selectors/demos/stars-rating/index.html, css/combined-selectors/index.md, css/combined-selectors/practice/realetive.md, css/tag-selector/demos/example/index.html, css/tag-selector/index.md
Причёсывает демо в статьях "Селектор по тегу" и "Комбинированные селекторы" (Issue #758)
=> Обновляет демо в статьях про селекторы

js/set/index.md
Судя по коду выше, количество элементов в множестве равно 5.
=> Исправляет ошибку в примере

.github/scripts/search-index.js
Фикс https://github.com/doka-guide/platform/issues/697 и https://github.com/doka-guide/platform/issues/650
=> Удаляет ссылки из текста при подготовке поискового индекса

js/async-in-js/practice/bespoyasov.md
Немного подправил раздел "На практике":
1. Поменял ссылку у `Promise.all`:
Ранее стояла ссылка на статью с [MDN](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/all), сейчас из [Доки](https://doka.guide/js/promise-all/).
2. Поправил пример кода `for await...of`:
Убрал ненужную `;`.
=> Вносит правки в статье "Асинхронность в JS"

css/attr/index.md, css/attr/practice/ezhkov.md
На страничке примеры были со скроллами. Кажется, что так чуть получше будет)
=> Добавил высоты ifram, чтобы контент отображался без скроллов

js/element-dataset/index.md
=> Правит пример из Element.dataset

js/element/index.md
=> Обновляет путь до демки

css/invalid-valid/demos/form-validation/index.html, css/invalid-valid/practice/ezhkov.md
=> Поправил статью про псевдоклассы :valid, :invalid

js/element-innerhtml/index.md
Исправляет ошибку в соответствии с https://github.com/doka-guide/content/issues/2473
=> Исправляет ошибку в примере кода innerHTML

css/background/index.md
=> Исправить битую ссылку

CODEOWNERS
=> Удаляет @skorobaeus

html/option/demos/default/images/arrow-down.svg, html/option/demos/default/index.html, html/option/demos/option-attrs/images/arrow-down.svg, html/option/demos/option-attrs/index.html, html/option/demos/option-styles/index.html, html/option/index.md, html/option/practice/ezhkov.md, html/select/demos/attributes/index.html, html/select/demos/basic/index.html, html/select/demos/custom/index.html
=> Обновляет демо в статье Option

.github/scripts/search-index.js, .github/workflows/update-index.yml
Fix: https://github.com/doka-guide/platform/issues/613
=> Использует LinkeDOM для извлечения текста для поискового индекса

js/array-reverse/index.md
=> Исправляет отображение заголовка [].reverse

css/index.md
=> Обновляет «Подключение стилей» в индексе

css/list-style-type/demos/list-style-type/index.html
=> Правит максимальную ширину в iframe в демке css/list-style-type

css/empty/demos/index/index.html
Учитывает предложения @cergmin вдогонку к ПР #2552
=> Фикс для демок в Empty

html/bdi/demos/basic/index.html, html/bdi/demos/userlist-b/index.html, html/bdi/demos/userlist-bdi/index.html, html/cite/demos/basic/index.html, html/del/demos/attributes/index.html, html/del/demos/basic/index.html, html/dfn/demos/basic/index.html, html/dfn/demos/link/index.html, html/ins/demos/attributes/index.html, html/ins/demos/basic/index.html, html/mark/demos/basic/index.html, html/small/demos/basic/index.html, html/sub/demos/basic/index.html, html/sub/demos/nested/index.html, html/sub/demos/variables/index.html, html/sup/demos/basic/index.html, html/sup/demos/nested/index.html, html/sup/demos/variables/index.html, html/u/demos/basic/index.html, html/u/demos/custom/index.html, html/var/demos/formula/index.html
Аналогичный PR для остальных демок как в PR #2553
=> Исправляет контент внутри iframe

html/div/index.md
- Чтобы избежать игнора
- Поправить неудачный вариант с апострофом
- Лучше описать картинку
FYI, обложка
=> Обновляет альт для обложки про div

people/ilfa/index.md, tools/markdown/practice/ilfa.md
Добавлен комментарий о поддержке видео и новый автор.
=> Добавлен комментарий "на практике" для статьи про markdown

CHANGELOG.md
Кажется, ничего не пропустила =)
=> Добавляет новые статьи в ченджлог

css/invalid-valid/demos/form-inputs/index.html, css/invalid-valid/demos/form-invalid/index.html, css/invalid-valid/demos/form-validation/index.html, css/invalid-valid/index.md, css/invalid-valid/practice/ezhkov.md
=> Обновляет демо в invalid-valid

tools/markdown/practice/ilfa.md
- Правит пути к картинке: http — https
- Обновляет альт к картинке на более точный
- Убирает лишний title ссылки, чтобы сделать снипет проще
- Нормализует снипеты и прочие мелочи
=> Редактирует совет про видео

js/local-storage/index.md
Исправление "widow" на "window"
=> Опечатка: "widow" - "window"

js/events/index.md
Remove duplicate word "function"
=> Удаляет задвоение слова «функция»

css/border-image/index.md, css/selection/demos/selection-with-text-shadow/index.html, css/selection/practice/rusakov.md, js/element-mouseover/index.md, js/events/index.md, js/modules/index.md
Чтобы код было проще читать в статьях и на узких экранах.
=> Подчищает примеры рисования кодом

css/after/demos/link/index.html, css/after/demos/word/index.html, css/after/index.md, css/after/practice/ezhkov.md, css/before/demos/empty-content/index.html, css/before/demos/icon/index.html, css/before/demos/list/index.html, css/before/index.md, css/before/practice/ezhkov.md
В фоновом режиме подтягиваю демки из раздела CSS к новым реалиям ✌
=> Апдейт демок в ::before и ::after

css/text-indent/index.md
Правит битый путь до демки. 
Было:
Стало:
[Сделано по подсказке Link Checker Action](https://github.com/doka-guide/content/runs/5002271108?check_suite_focus=true)
=> Правит путь до демки

css/caret-color/index.md
Иначе не очень хорошо, [см. caret-color](https://doka.guide/css/caret-color/)
=> Сандбоксит автофокус, чтобы не было прыжка

css/nesting-selector/demos/nested-selector/index.html, css/nesting-selector/index.md, css/selector-list/demos/enumerous-selector/index.html, css/selector-list/index.md
Редизайнит демки в "Селектор потомка" и "Перечисление селекторов"
=> Редизайнит демки в статьях о Селекторах

css/checked/demos/check/images/arrow-down.svg, css/checked/demos/check/index.html, css/checked/demos/choose/index.html, css/checked/index.md, css/checked/practice/solarrust.md, css/placeholder/demos/example/index.html, css/placeholder/index.md
Подтянула диз и заменила в первом демо в `:checked` обводку на прозрачность, потому что радиокнопки с обводкой были слишком прекрасны :D
=> Редизайнит демки в `::placeholder` и `:checked`

people/blueingreen68/index.md, people/romanbarannickov/index.md
Повелось, что у авторов идёт сначала имя, потом фамилия. Поправила два случая, где это было не так =)
=> Ставит имя автора перед фамилией

css/box-shadow/demos/button/index.html, css/box-shadow/demos/neon/index.html, css/box-shadow/demos/pixelart/index.html, css/box-shadow/demos/skeuomorph/index.html, css/box-shadow/index.md, css/box-shadow/practice/mefody.md, css/box-shadow/practice/solarrust.md
Редизайнит демки в зафичеренной сейчас Box-shadow.
=> Редизайнит Box-shadow

CODEOWNERS
Добавляет Вадима в редакторы разделов HTML и CSS
=> Правит CODEOWNERS

js/modules/index.md
Добавил открывающую скобку в сниппете
=> Правит опечатку в статье про модули

people/timbilalov/index.md
@timbilalov привет! В пылу редактуры твоей статьи мы забыли добавить информацию о тебе в папку _people/_. Я имела смелость добавить твоё имя и ссылку на твой сайт. Посмотри, пожалуйста, ок ли это или нужно что-то исправить. Только тебе решать какая инфа будет видна на сайте =)
=> Добавляет @timbilalov в папку people

people/anatoly-kor/index.md
@anatoly-kor забыли тебя подписать. Напиши своё имя и ссылку если хочешь указать другие соцсети
=> Добавляет автора статьи Вим

.github/workflows/product-deploy.yml
Связано с [ишью](https://github.com/doka-guide/platform/issues/915)
=> Исправляет генерацию ссылок в футере

css/transform-function/demos/funcs-order/index.html, css/transform-function/demos/funcs-right-order/index.html, css/transform-function/index.md
Минорный фикс к #2838, потому что я забыла сохранить изменения 😬
=> Фикс вдогонку к ПР #2838

js/var-let/index.md
=> Правит опечатку в статье про VAR и LET

css/index.md, html/index.md
Добавила новые статьи с индексы разделов HTML и CSS
=> Обновляет индексы HTML и CSS

html/form/index.md
Статья была отредактирована в рамках https://github.com/doka-guide/content/pull/2070/, но забыт тег редактора. Добавляет тег.
=> Добавляет редактора в статью form

recipes/index.md
Один рецепт в разделе повис без подкатегории. Предложила назвать эту подкатегорию «Интерфейс»
=> Добавляет забытому рецепту подкатегорию

html/form/demos/email/index.html, html/form/demos/forms/index.html, html/img/demos/img-fix-width/index.html, html/img/demos/img-overlay/index.html, html/nav/demos/breadcrumbs/bikes/bmx/index.html, html/nav/demos/breadcrumbs/bikes/bmx/jump-bike-3000/index.html, html/nav/demos/breadcrumbs/bikes/index.html
Причёсывает демки в статьях для фичеринга в разделе HTML (добавляет недостающий адаптив) #2876
=> Причёсывает демки для фичеринга (HTML)

js/infinite-scroll/index.md
Добавляет в примере кода пропущенный аргумент при вызове throttle
=> Добавляет в примере кода пропущенный аргумент при вызове throttle

css/attr/demos/print-link/index.html, css/attr/demos/tooltip/index.html, css/attr/index.md, css/attr/practice/ezhkov.md
Добавляет диз для демок в статье attr() #2876
=> Добавляет диз в attr() (CSS) [2/3]

CHANGELOG.md
=> Обновляет список изменений на март/апрель

js/event/index.md
Напрямую свойство CustomEvent добавить не можно. Оно должно лежать в свойстве detail
Closes #
=> Уточняет создание кастомных событий

js/map/index.md
Правит зарепорченный баг
Closes #2939
=> Исправляет порядок аргументов в forEach для map

recipes/lets-encrypt-nginx/index.md, recipes/progress/index.md, recipes/short-links/index.md, recipes/snow/index.md
=> Заменяет тег doka на article в рецептах

js/element-touch/demos/Windrushfarer-KKgZGEq/index.html, js/element-touch/demos/Windrushfarer-RwGjopb/index.html
В этой статье хорошо побуждают использовать мобильный девайс. Например:
> Рисовалка ниже использует поля события и типы событий касаний. Используйте смартфон, так как касания не работают при использовании мыши.
Однако читатель может взгрустнуть, рисуя свои узоры на "холсте", ведь скролл будет дергаться и портить все удовольствие.
(правки в уже существующих файлах)
=> Улучшает примеры про `Событие touch`

js/architecture-and-design-patterns/index.md
=> добавляет описание, связанные статьи в статью про архитектурну и паттерны

css/backface-visibility/index.md
=> Правит мелочи в доке про `backface-visibility`

css/backdrop-filter/index.md
=> Правит мелочи в доке про `backdrop-filter`

css/attribute-selector/index.md
=> Правит мелочи в доке про Селектор по атрибуту

css/appearance/index.md
=> Правит мелочи в доке про `appearance`

css/animation-timing-function/index.md
=> Правит мелочи в доке про `animation-timing-function`

css/background/index.md
=> Правит мелочи в доке про `background`

html/a/index.md
Добавляет описание и связанные статьи в рамках хакатона.
=> Добавляет дескрипшн и связанные статьи к доке про `a`

html/audio/index.md
Добавляет описание и связанные статьи в рамках хакатона.
=> Добавляет дескрипшн и связанные статьи к доке про `audio`

css/active/index.md
=> Правит мелочи в доке про `:active`

css/after/index.md
=> Правит мелочи в доке про `::after`

css/all/index.md
=> Правит мелочи в доке про `all`

css/animation/index.md
=> Правит мелочи в статье про `CSS-анимации`

css/animation-delay/index.md
=> Правит мелочи в доке про `animation-delay`

css/animation-direction/index.md
=> Правит мелочи в доке про `animation-direction`

css/animation-duration/index.md
=> Правит мелочи в доке про `animation-duration`

html/autocomplete/index.md
Добавляет описание и связанные статьи в рамках хакатона.
=> Добавляет дескрипшн и связанные статьи к доке про `autocomplete`

css/animation-fill-mode/index.md
=> Правит мелочи в доке про `animation-fill-mode`

css/animation-iteration-count/index.md
=> Правит мелочи в доке про `animation-iteration-count`

css/animation-name/index.md
=> Правит мелочи в доке про `animation-name`

css/animation-play-state/index.md
=> Правит мелочи в доке про `animation-play-state`

css/align-content/index.md, css/animation-delay/index.md, css/animation-duration/index.md, css/animation-timing-function/index.md
Исправлена проблема со сборкой сайта. Это происходило, поскольку пути в мете были неправильными.
=> Исправляет пути к материалам

html/base/index.md
Добавляет связанные статьи в рамках хакатона.
=> Добавляет связанные статьи к доке про `base`

css/background-image/index.md
=> Правит мелочи в доке `background-image`

css/background-clip/index.md
=> Правит мелочи в доке `background-clip`

css/background-blend-mode/index.md
=> Правит мелочи в доке `background-blend-mode`

css/border-radius/index.md
=> Мелкие правки в доку про `border-radius`

css/border-image/index.md
=> Мелкие правки в доку про `border-image`

css/border/index.md
=> Мелкие правки в доку про `border`

css/before/index.md
=> Мелкие правки в доку про `before`

.github/scripts/description-helper.js, .github/workflows/maintainer-helper.yml
В продолжение обсуждения на созвоне. Дорабатывает экшен чтобы при слиянии в мейн выполнялась проверка дескрипшенов и обновлялся список в соответствующем ишью.
Я не знаю, работает ли, но сделала по образу и подобию существующих проверок 😅
Чуть поменяла порядок составления списка. Если дескрипшена нет, то будет в начале списка, если есть — то попадёт в конец.
=> Добавляет экшен для автозадач по проверке дескрипшенов

pages/about/index.md
1. Перенесла Олю с блок «особая благодарность»
1. Добавила Сашу в команду
1. Актуализировала свою роль
Closes #
=> Актуализирует команду

settings/featured.md
=> Обновляет фичеринг

html/b/index.md
Добавляет описание и связанные статьи в рамках хакатона.
=> Добавляет дескрипшн и связанные статьи к доке про `b`

css/index.md, css/repeating-conic-gradient/demos/basic/index.html, css/repeating-conic-gradient/demos/pattern/index.html, css/repeating-conic-gradient/demos/repeating/index.html, css/repeating-conic-gradient/index.md
=> Добавляет доку про `repeating-conic-gradient`

css/child/index.md
=> Вносит правки в доку про `child`

css/class-selector/index.md
=> Вносит правки в доку про Селектор по классу

css/clip/index.md
=> Вносит правки в доку про `clip`

css/caret-color/demos/rainbow-input/index.html, css/caret-color/index.md, css/caret-color/practice/mishamad.md
=> Вносит правки в доку про `caret-color`

css/cascade/index.md
Слэш на конце не позволял сайту корректно собираться. Ошибка исправлена! :)
=> Исправляет ссылку

js/array-isarray/index.md
=> добавляет описание, связанные статьи в статью про Array.isArray

js/array-length/index.md
=> добавляет описание, связанные статьи в статью про length

css/column-count/index.md
=> Вносит правки в доку про `column-count`

js/function-context/index.md
at line 338 -> // Good morning, Ivan :-D
Closes #
=> Добавляет забытый комментарий

css/column-fill/index.md
=> Добавляет описание и связанные статьи для `column-fill`

css/column-row-gap/index.md
=> Добавляет описание и связанные статьи для `column-gap`, `row-gap`

css/column-rule-color/index.md
=> Добавляет описание и связанные статьи для `column-rule-color`

css/column-span/index.md
=> Добавляет описание и связанные статьи для `column-span`

css/column-width/index.md
=> Добавляет описание и связанные статьи для `column-width`

css/columns/index.md
=> Добавляет описание и связанные статьи для `columns`

css/combined-selectors/index.md
=> Добавляет описание и связанные статьи для комбинированных селекторов

css/comments/index.md
=> Добавляет описание и связанные статьи для комментариев в css

css/conic-gradient/index.md
=> Добавляет описание и связанные статьи для `conic-gradient()`

css/counter-increment/index.md
=> Добавляет описание и связанные статьи для `counter-increment`

css/counter-reset/index.md
=> Добавляет описание и связанные статьи для `counter-reset`

css/currentcolor/index.md
=> Добавляет описание и связанные статьи для `currentColor`

css/css-rule/index.md
=> Добавляет описание и связанные статьи для css-правила

js/browsers-storages/index.md
=> добавляет описание и связанные статьи в статью про хранение данных в браузере

js/clean-architecture/index.md
=> добавляет описание и связанные статьи в статью про трёхслойную архитектуру

js/code-style/index.md
=> добавляет связанные статьи в статью про стиль написания кода

js/design-patterns-structural/index.md
=> добавляет связанные статьи в статью о структурных паттернах проектирования

js/design-patterns-creational/index.md
=> добавляет связанные статьи в статью о порождающих паттернах проектирования

js/design-patterns-behaviorial/index.md
=> добавляет связанные статьи в статью о поведенческих паттернах проектирования

pages/about/index.md
Переводит меня из списка редакции в особую благодарность
=> Переводит меня в бывшие

js/element-focus/index.md
=> добавляет связанные статьи в доку о методе focus

js/element-getattribute/index.md
=> добавляет связанные статьи в доку о методе getAttribute

js/element-hidden/index.md
=> добавляет связанные статьи в доку о свойстве hidden

js/function-context/index.md, js/function-context/practice/bespoyasov.md
=> добавляет связанные статьи в доку о this

js/integration-and-system-testing/index.md
=> добавляет связанные статьи в статью об интеграционном тестировании

js/local-storage/index.md, js/local-storage/practice/akellbl4.md
=> добавляет связанные статьи в доку о localstorage

js/modules/index.md, js/modules/practice/bespoyasov.md
=> добавляет связанные статьи в статью о модулях

js/null-primitive/index.md
=> добавляет связанные статьи в доку null

js/object/index.md
=> добавляет связанные статьи в доку о Object

css/linear-gradient/index.md, css/repeating-linear-gradient/demos/basic/index.html, css/repeating-linear-gradient/demos/blurred_gradient/index.html, css/repeating-linear-gradient/demos/zebra_linear-gradient/index.html, css/repeating-linear-gradient/demos/zebra_repeating-linear-gradient/index.html, css/repeating-linear-gradient/index.md
=> Добавляет доку про repeating-linear-gradient()

CHANGELOG.md
Добавляет статью за июль в ченджлог.
Как-то удивительно мало, всего 1 статья. @nlopin перепроверь меня, пожалуйста
=> Добавляет статьи за июль 2022 в ченджлог

js/performance/index.md
=> добавляет связанные статьи в доку о performance

js/programming-paradigms/index.md, js/programming-paradigms/practice/bespoyasov.md
=> добавляет связанные статьи в статью о парадигмах программирования

js/set-size/index.md
=> добавляет связанные статьи в доку о свойстве size для set

js/set-constructor/index.md
=> добавляет связанные статьи в доку о конструкторе для set

js/set-clear/index.md
=> добавляет связанные статьи в доку о методе clear для set

tools/web-server/index.md
=> добавляет связанные статьи в статью о веб-серверах

tools/webpack/index.md, tools/webpack/practice/igorkamyshev.md
=> добавляет связанные статьи в статью о Webpack

tools/gulp/index.md
=> добавляет связанные статьи в статью о gulp

tools/nodejs/index.md
=> добавляет связанные статьи в статью о node.js

tools/version-control/index.md
=> добавляет связанные статьи в статью о гите

tools/ssl-certificates/index.md
=> добавляет связанные статьи в статью о SSL

tools/agile/index.md
=> добавляет связанные статьи в статью о agile

tools/apache-web-server/index.md
=> добавляет связанные статьи в статью о Apache Server

tools/code-review/index.md
=> добавляет связанные статьи в статью о code review

tools/docker-compose/index.md
=> добавляет связанные статьи в статью о Docker Compose

tools/elasticsearch/index.md
=> добавляет связанные статьи в статью о Elasticsearch

tools/gitlab-ci-cd/index.md
=> добавляет связанные статьи в статью о gitlab ci/cd

tools/microservices/index.md
=> добавляет связанные статьи в статью о микросервисах

tools/site-readers/index.md
=> добавляет связанные статьи в статью о SEO и скринридерах

tools/ssh/index.md
=> добавляет связанные статьи в статью о SSH

js/typecasting/index.md, js/typecasting/practice/bespoyasov.md
=> добавляет связанные статьи в статью о приведении типов

js/urlsearchparams/index.md, js/urlsearchparams/practice/akellbl4.md
=> добавляет связанные статьи в доку о URLSearchParams

js/technical-debt/index.md
=> добавляет связанные статьи в статью о тех.долге

js/tdd/index.md
=> добавляет связанные статьи в статью о TDD

tools/http-protocol/index.md
=> добавляет связанные статьи в статью о HTTP

js/array-reduce/practice/windrushfarer.md
Fix name of the function filterEven
Closes #
=> Исправляет имя функции

pages/about/index.md
Правит должность у @skorobaeus так, чтобы она совпадала с реальностью.
=> Меняет @skorobaeus должность

js/if-else/practice/saharok.md
Заменил дефис на тире, а также поправил правописание предлога "в отличие".
=> Исправляет опечатки в статье про if-else

html/bdi/index.md
=> добавляет связанные статьи в доку bdi

html/body/index.md
=> добавляет связанные статьи в доку body

html/cite/index.md
=> добавляет связанные статьи в доку cite

html/code/index.md
=> добавляет связанные статьи в доку code

html/comments/index.md
=> добавляет связанные статьи в доку про комментарии в HTML

html/data/index.md
=> добавляет связанные статьи в доку про <data>

html/button/index.md
=> добавляет связанные статьи в доку button

html/caption/index.md
=> добавляет связанные статьи в доку caption

html/del/index.md
=> добавляет связанные статьи в доку про <del>

js/element-classlist/index.md, js/element-classlist/practice/windrushfarer.md
Случайно нашёл немного опечаток внутри, предлагаю исправить.
=> Исправляет опечатки в доке про `classList`

html/dfn/index.md
=> добавляет связанные статьи в доку про <dfn>

html/video/index.md
=> добавляет связанные статьи в доку про <video>

html/value/index.md
=> добавляет связанные статьи в доку про атрибут value

html/tables/index.md
=> добавляет связанные статьи в доку про таблицы

html/strong/index.md
=> добавляет связанные статьи в доку про <strong>

html/source/index.md
=> добавляет связанные статьи в доку про <source>

html/section/index.md
=> добавляет связанные статьи в доку про <section>

html/span/index.md
=> добавляет связанные статьи в доку про <span>

html/screenreaders/index.md
=> добавляет связанные статьи в доку про скринридеры

html/samp/index.md
=> добавляет связанные статьи в доку про <samp>

html/s/index.md
=> добавляет связанные статьи в доку про <s>

html/select/index.md
=> добавляет связанные статьи в доку про <select>

html/picture/index.md
=> добавляет связанные статьи в доку про <picture>

html/pattern/index.md
=> добавляет связанные статьи в доку про атрибут pattern

html/pre/index.md
=> добавляет связанные статьи в доку про <pre>

html/optgroup/index.md
=> добавляет связанные статьи в доку про <optgroup>

html/object/index.md
=> добавляет связанные статьи в доку про <object>

html/p/index.md
=> добавляет связанные статьи в доку про <p>

html/option/index.md
=> добавляет связанные статьи в доку про <option>

html/mark/index.md
=> добавляет связанные статьи в доку про <mark>

html/link/index.md
=> добавляет связанные статьи в доку про <link>

html/main/index.md
=> добавляет связанные статьи в доку про <main>

html/label/index.md
=> добавляет связанные статьи в доку про <label>

html/ins/index.md
=> добавляет связанные статьи в доку про <ins>

html/img/index.md
=> добавляет связанные статьи в доку про <image>

html/iframe/index.md
=> добавляет связанные статьи в доку про <iframe>

html/header/index.md
=> добавляет связанные статьи в доку про <header>

html/head/index.md
=> добавляет связанные статьи в доку про <head>

html/global-attrs/index.md
=> добавляет связанные статьи в доку про глобальные атрибуты

html/footer/index.md
=> добавляет связанные статьи в доку про <footer>

html/figure-figcaption/index.md
=> добавляет связанные статьи в доку про <figure>

html/dl-dd-dt/index.md
=> добавляет связанные статьи в доку про <dl>

js/set-values/index.md
=> changing the wrong iterator name

js/set-delete/index.md
=> fixed typo in method name

a11y/prefers-reduced-motion/index.md
=> Добавляет плейсходер для доки про prefers-reduced-motion

a11y/role-link/index.md
=> Добавляет плейсхолдер для роли link

a11y/role-img-image/index.md
=> Добавляет плейсхолдео для ролей img, image

a11y/aria-required/index.md
=> Добавляет плейсхолдер для доки про aria-required

a11y/role-button/index.md
=> Добавляет плейсхолдер для доки про роль button

a11y/role-navigation/index.md
=> Добавляет плейсхолдер для доки про роль navigation

a11y/role-search/index.md
=> Добавляет плейсхолдер для доки про роль search

a11y/index.md
Обновлённый индекс для раздала о доступности ✨
=> Обновляет index.md для раздела Доступность

.github/checklist_new_article.md, .github/checklist_new_doka.md
Вместо `demos.md` поставил `/demos/index.md`
=> Заменяет битые ссылки в чек-листах

js/promise-all/practice/yurlovr.md
В теме Promise.all() в разделе "На практике" в примере используется переменная arrayFetchUsers без объявления.
=> Используется переменная без её объявления

js/array-from/index.md
Мы создали set newNumbers, но используем метод .add не на newNumbers, а на uniqueThings, но позже мы вызываем uniqueNumbers, => тут опечатка.
=> Опечатка в примере "Массив из Set" про Array.from()

js/bom/practice/bespoyasov.md
=> Опечатка в слове 'console'

js/architecture-mvc/index.md
Небольшая правка примера кода, используется параметр из функции
Closes #
=> Правит пример кода в тонком контроллере

a11y/aria-haspopup/index.md
=> Добавляет плейсхолдер для доки про aria-haspopup

CODEOWNERS
=> Добавляет @hellsquirrel в CODEOWNERS

a11y/role-link/index.md
Переликовала с другими доками.
=> Добавляет ссылки в плейсхолдер доки про роль `link`

a11y/aria-atomic/index.md
=> Добавляет ссылки в плейсхолдер доки про `aria-atomic`

CODEOWNERS
=> Добавляет @TatianaFokina к разделам с вёрсткой.

CHANGELOG.md
Создала сентябрь в ченджлоге.
@TatianaFokina мы руками вносим новые материалы в этот список и сливаем в конце месяца. Предлагаю дополнить этот файл материалами по доступности после релиза раздела, чтобы они тоже были учтены =)
=> Добавляет сентябрь в ченджлог

html/placeholder/demos/example/index.html, html/placeholder/index.md
Поправил демку со всеми советами стайлгайда
Ссылочка на красоту, чтобы долго не искать: https://content-3855.dev.doka.guide/html/placeholder/
=> Украшает демку для `placeholder`

css/box-sizing/demos/box-sizing/index.html, css/box-sizing/index.md
Поставил демку по центру, раскрасил в цвета раздела и уменьшил `iframe` до размеров демки.
Ссылка, чтобы долго не искать: https://content-3871.dev.doka.guide/css/box-sizing/
=> Украшает демку для `box-sizing`

css/combined-selectors/demos/stars-rating-bug/index.html, css/combined-selectors/demos/stars-rating/index.html, css/combined-selectors/practice/romanbarannickov.md
Уменьшил iframe по размеру демок и добавил звёздам нижний падинг, чтобы визуально их выровнять.
Ссылка: https://content-3883.dev.doka.guide/css/combined-selectors/
=> Причёсывает демки в Комбинированных селекторах

css/var/index.md
Предлагаю исправить пару опечаток в блоке с кодом.
=> Правит опечатку в статье про `var`

css/pseudoclasses/demos/custom-checkbox/index.html, css/pseudoclasses/demos/default/index.html, css/pseudoclasses/demos/disabled-enabled/index.html, css/pseudoclasses/demos/empty/index.html, css/pseudoclasses/demos/indeterminate/index.html, css/pseudoclasses/demos/range/index.html, css/pseudoclasses/demos/row-hover/index.html, css/pseudoclasses/demos/target/index.html, css/pseudoclasses/index.md
Сделал адаптив для всех демок, поставил их посередине.
~С демкой indeterminate вышло спорно. Не уверен, как сделать, чтобы выглядело хорошо на 360 экранах и чтобы радиокнопки не липли друг к другу. Ещё можно увеличить под эту демку iframe до 470 или, чтоб наверняка, 490, но тогда на десктопе может слишком щедро смотреться 🤷‍♀️~
Ссылка: https://content-3884.dev.doka.guide/css/pseudoclasses/
=> Адаптирует демки в Псевдоклассах

pages/licenses/index.md
Раньше ссылка была битая. Теперь нет.
=> Фиксит ссылку на правообладателя шрифта

docs/demos/style.md
В стайлгайде не было состояния фокуса у этих кнопок. Теперь есть.
=> Добавляет фокус радио-кнопкам и чекбоксам

a11y/index.md
Удалила старые огромные подразделы, заменила их более атомарными, добавила новые материалы.
=> Обновляет индекс раздела Доступность

.github/workflows/pr-add-checklist.yml
Меняет триггер воркфлоу, на тот, который обладает правами на запись
=> Фиксит экшен чеклистов

.github/workflows/pr-labels.yml
Переключает лейблер с релизной ветки на сам релиз
=> Переключает лейблер на официальный релиз

.github/scripts/demos-helper.js, .github/scripts/description-helper.js, .github/scripts/editor-helper.js
Добавил три списка для этого:
1. [Редактура: Доступность](https://github.com/doka-guide/content/issues/3956)
2. [Дескрипшены: Доступность](https://github.com/doka-guide/content/issues/3955)
3. [Демки: Доступность](https://github.com/doka-guide/content/issues/3954)
Fix #3953
=> Добавляет чеккер для раздела Доступность

new.sh
Добавила новый раздел Доступность в скрипт _new.sh_.
=> Добавляет доступность в new.sh

.gitignore
=> Добавляет .gitignore

pages/about/index.md
Обновляет информацию в about про новый раздел
=> Добавляет информацию about о @TatianaFokina

people/hellsquirrel/index.md, people/walborn/index.md
=> Добавляет оставшиеся ачивки

css/scroll-padding/index.md
=> Исправляет опечатку

a11y/index.md, a11y/role-alert/index.md, a11y/role-banner/index.md, a11y/role-button/index.md, a11y/role-complementary/index.md, a11y/role-contentinfo/demos/footer-with-contentinfo/index.html, a11y/role-contentinfo/index.md, a11y/role-form/index.md, a11y/role-heading/index.md, a11y/role-img-image/index.md, a11y/role-link/index.md, a11y/role-log/index.md, a11y/role-main/index.md, a11y/role-marquee/index.md, a11y/role-navigation/index.md, a11y/role-presentation-none/demos/decorative-hr/index.html, a11y/role-presentation-none/index.md, a11y/role-region/index.md, a11y/role-search/index.md, a11y/role-status/index.md, a11y/role-timer/index.md
Изменила названия док про роли и добавила в индекс раздела новые подразделы.
=> Обновляет названия док и индекс раздела Доступность

css/css-counters/demos/reset-example/index.html, css/css-counters/index.md
Исправил пару ошибок в тексте и обновил демку
=> Правит текст и обновляет демку

html/datalist/index.md
Исправление ошибки в аттрибутах тега
=> Исправлена ошибка label->value

css/transform-function/index.md
В последних версиях Chrome и Safari второй пример в конце раздела «Подсказки» корректно отображается, поэтому информация неактуальна. См. также: https://caniuse.com/?search=translate
=> Обновляет информацию о частичной поддержке браузерами для примера из статьи `Функции CSS-трансформации`

css/css-counters/demos/set-example/index.html
Обновляет значение "counter-increment" для последнего элемента и его текст.
=> Обновляет демку и текст

css/css-counters/index.md
В подразделе "counter-set" в коде правит текст третьего элемента.
=> Правит текст

js/debounce/index.md
Пропущено получение searchForm
=>  Добавляет ссылку на форму поиска в примере про `debounce`

new.sh
В Доке появилась новая рубрика «На собеседовании». Данные изменения вносят корректировки в работу скрипта для сборки новых материалов.
=> Добавляет новые типы материалов из рубрики «На собесе»

css/list-style/index.md
=> Исправляет опечатку в статье о свойстве `list-style`

CHANGELOG.md
=> Добавляет ноябрь в ченджлог

css/index.md
=> Обновляет индекс CSS

.github/workflows/pr-preview.yml
=> Исправляет формирование переменной с пробелами

CHANGELOG.md
=> Добавляет декабрь в ченджлог

people/nlopin/index.md
У нас плашки «Редакция» висят на всех, кто в актуальной команде редакции, а на тех, кто уже не в актуальной команде — не висят. Убирает плашку.
=> Правит профиль Коли, убирает плашку редакции

css/font-variant-ligatures/index.md, css/font-variant-numeric/index.md, css/font-variant-position/index.md, css/font-variant/index.md, css/font-variation-settings/index.md, css/font-weight/index.md, css/font/index.md
Очередная порция для задачки #3009
=> CSS: добавляет описания и связанные статьи

CHANGELOG.md
Добавила новый месяц в ченджлог.
=> Добавляет январь в ченджлог

js/element-keydown/index.md, js/element-keyup/index.md
Моего контрибьюта в этих статьях теперь нет, так что я убрала себя из списка участников)
=> Удаляет skorobaeus из списка контрибьюторов в статьях keydown и keyup

js/array-length/index.md
=> Исправил неправильную переменную в `.length`

CHANGELOG.md
=> Добавляет февраль в ченджлог

README.md
Добавила бэджик линк чекера на главную репозитория
=> Добавляет бэджик линк чекера

CODEOWNERS
=> Временное изменение CODEOWNERS

css/cascade/index.md
=> Исправляет имя Эрик (Ерик —> Эрик)

people/rrramble/index.md
Добавила нового контрибьютора в отдельном пиаре, чтобы можно было помёрджить несколько пиаров с его участием и не поломать link checker.
=> Добавляет нового контрибьютора

tools/design-patterns-creational/index.md
Исправление небольшой неточности
=> Исправляет неточность в «Порождающие паттерны проектирования»

CODEOWNERS
Убрала себя из CSS и HTML. Нет больше над ними моей власти!
=> Убирает себя из CODEOWNERS

js/var-let/index.md
Сам пул-реквест короткий и понятный. Если углубляться в дополнение статьи по спеке, можно зависнуть надолго.
Точнее: 
> Для имени переменной можно использовать следующие символы:
> 
> буквы латинского алфавита;
> цифры;
> символы $ и _.
> Первый символ не должен быть цифрой:
По спеке первый символ и "продолжающие" должны соответствовать `_` или `$` или unicode символы "со свойствами" `ID_Start` и `ID_Continue`. Набор символов в целом гуглится, перечислить его естественно невозможно.
Может ради пометки дать пример что `const 𝜋 = 3.14` валидная конструкция тоже, но пожалуйста не надо😂
=> Исправляет пример в статье про переменные

js/var-let/index.md
Полагаю здесь нужно было выводить значение переменной 'a', а не число.
=> Update index.md в "Переменные const, let и var"

CHANGELOG.md
Новый ченджлог за апрель 2023.
=> Добавляет апрель в ченджлог

recipes/index.md
Внесла в индекс статьи, которых там не было.
Переименовала «фишки из прошлого» в «ради веселья». Хотела «Just for fun», но надо на русском. Если придумаете более удачный перевод — будет супер. 
Добавила раздел «Рутина», в который попала статья про конвертор шрифтов. В другие разделы, кажется, она не очень влезает. В теории там может быть ещё много статей с описанием решения рутинных задачек. 
Любые пожелания, предложения, правки приветствуются!
=> Обновляет индекс раздела Рецепты

recipes/center/index.md
Была обнаружена неаккуратная копипаста. Копипаста была успешно исправлена
^_~
=> Исправляет путь до демки

a11y/role-menuitemradio/index.md
Заменила ссылку на существующую.
=> Исправляет ссылку на рекомендуемую статью

CHANGELOG.md
=> Добавляет май в ченджлог

a11y/index.md, a11y/role-tree/index.md
=> Добавляет плейсхолдер для роли `tree`

a11y/index.md, a11y/role-treeitem/index.md
=> Добавляет плейсхолдер для роли `treeitem`

a11y/aria-valuetext/index.md
=> Добавляет плейсхолдер для `aria-valuetext`

a11y/aria-valuenow/index.md
=> Добавляет плейсхолдер для `aria-valuenow`

a11y/aria-posinset/index.md, a11y/index.md
=> Добавляет плейсхолдер для `aria-posinset`

people/inventoris/index.md
Наш способ сказать «Спасибо» за вклад в проект и его популяризацию ♥️
🚨 Сперва надо слить https://github.com/doka-guide/platform/pull/1160 в платформу!
=> Новый значок для @inventoris

CHANGELOG.md
=> Добавляет июнь в ченджлог

a11y/role-gridcell/index.md
=> Добавляет плейсхолдер для роли `gridcell`

a11y/aria-valuemin/index.md
=> Добавляет плейсхолдер для `aria-valuemin`

a11y/aria-valuemax/index.md
=> Добавляет плейсхолдер для `aria-valuemax`

css/text-transform/index.md, css/transform-style/index.md, css/vertical-align/index.md, css/z-index/index.md
Исправляю ошибку, которая упала при сборке.
@solarrust, посмотри, норм ли исправленные рекомендуемые материалы, которые добавила вместо пока несуществующих.
```
Проверка для всех файлов
npm WARN exec The following package was not found and will be installed: yaml-cat@0.4.2
result.json
Поле related в файле css/text-transform/index.md содержит ошибки:
- материала по пути 'css/text-underline' не существует
,- материала по пути 'css/trasform' не существует
Поле related в файле css/transform-style/index.md содержит ошибки:
- материала по пути 'css/translate' не существует
Поле related в файле css/vertical-align/index.md содержит ошибки:
- материала по пути 'css/flex-guide' не существует
Поле deescription не входит в список разрешённых полей
Error: Process completed with exit code 1.
```
=> Исправляет ошибки Frontmatter lint

a11y/aria-colindex/index.md
=> Добавляет плейсхолдер для `aria-colindex`

a11y/aria-rowspan/index.md
=> Добавляет плейсхолдер для `aria-rowspan`

a11y/aria-rowindex/index.md
=> Добавляет плейсхолдер для `aria-rowindex`

a11y/role-listitem/index.md
=> Добавляет плейсхолдер для `listitem`

a11y/role-application/index.md
=> Добавляет плейсхолдер для `application`

a11y/role-math/index.md
=> Добавляет плейсхолдер для `math`

a11y/aria-valuemax/index.md
=> Исправляет ошибку Frontmatter Lint

a11y/role-scrollbar/index.md
=> Добавляет плейсхолдер для `scrollbar`

a11y/role-slider/index.md
=> Добавляет плейсхолдер для `slider`

a11y/role-term/index.md
=> Добавляет плейсхолдер для `term`

a11y/role-time/index.md
=> Добавляет плейсхолдер `time`

a11y/role-textbox/index.md
=> Добавляет плейсхолдер `textbox`

a11y/role-searchbox/index.md
=> Добавляет плейсхолдер `searchbox`

a11y/aria-roles/index.md, a11y/role-caption/index.md
=> Добавляет плейсхолдер `caption`

a11y/role-code/index.md
=> Добавляет плейсхолдер `code`

a11y/role-definition/index.md
=> Добавляет плейсхолдер `definition`

a11y/aria-rowindextext/index.md, a11y/role-caption/index.md, a11y/role-figure/index.md
Исправила неправильные ссылки на некоторые статьи.
=> Исправляет неправильные ссылки

a11y/role-cell/index.md
=> Добавляет плейсхолдер `cell`

a11y/role-meter/index.md
=> Добавляет плейсхолдер `meter`

a11y/role-option/index.md
=> Добавляет плейсхолдер `option`

a11y/role-spinbutton/index.md
=> Добавляет плейсхолдер `spinbutton`

a11y/role-progressbar/index.md
Исправила ссылки и название тега 😅 Снова!
=> Исправляет ссылки

a11y/role-columnheader/index.md
=> Добавляет плейсхолдер `columnheader`

a11y/role-emphasis/index.md
=> Добавляет плейсхолдер `emphasis`

a11y/role-group/index.md
=> Добавляет плейсхолдер `group`

a11y/role-paragraph/index.md
=> Добавляет плейсхолдер `paragraph`

a11y/role-rowgroup/index.md
=> Добавляет плейсхолдер `rowgroup`

a11y/role-superscript/index.md
После этой группы плейсхолдеров закину 7 последних, и эпопея с плейсхолдерами, наконец, закончится 🎉
=> Добавляет плейсхолдер `superscript`

a11y/role-subscript/index.md
=> Добавляет плейсхолдер для `subscript`

a11y/role-deletion/index.md
Пришло время последних семи плейсхолдеров!
=> Добавляет плейсхолдер `deletion`

a11y/role-insertion/index.md
Пришло время последних семи плейсхолдеров!
=> Добавляет плейсхолдер `insertion`

a11y/role-strong/index.md
И это последний плейсхолдер. Спасибо всем за ревью и апрувы ❤️
=> Добавляет плейсхолдер `strong`

CODEOWNERS
=> Добавляет Свету в кодовнерсы для ревью демок

css/accent-color/demos/base/index.html, css/accent-color/index.md
Упростил демку, присыпал стилями из стайлгайда
Было:
Стало:
https://content-4642.dev.doka.guide/css/accent-color/
P.S. Пока что ПР с изменением чекбоксов попридержу, подожду, когда их побольше поднакопится
=> Обновляет демку в `accent-color`

css/background-image/demos/fix-2/index.html, css/background-image/demos/fix/index.html, css/background-image/demos/gradient/index.html, css/background-image/practice/solarrust.md
Добавил адаптивов и немного поменял стили
@solarrust, пожалуйста, посмотри, потому что я из твоего совета повырезал немного текста, чтобы в сниппетах оставалось только нужное. Вдруг я чего-то лишнего убрал
Было:
Стало:
Было2:
Стало2:
https://content-4650.dev.doka.guide/css/background-image/
=> Обновляет демки в `background-image`

css/border-style/demos/all/index.html, css/border-style/index.md
Чуть-чуть поменял демку
Было:
Стало:
https://content-4668.dev.doka.guide/css/border-style/
=> Обновляет демку в `border-style`

css/accent-color/index.md, css/all/index.md, css/animation-fill-mode/index.md, css/animation-timing-function/index.md, css/animation/index.md, css/aspect-ratio/index.md, css/attribute-selector/index.md, css/background-color/index.md, css/background-size/index.md, css/border-block/index.md, css/border-color/index.md, css/border-style/index.md, css/border/index.md, css/box-model/index.md
Мы с @solarrust в #4676 договорились, что я добавлю себя в контрибьтеры одним ПРом во все доки, что контрибьютил 👀
По мотивам:
* #4642
* #4644
* #4645
* #4646
* #4647
* #4648
* #4650
* #4652
* #4654
* #4655
* #4656
* #4668
* #4674
=> Добавляет @StarHamster в контрибьюторы

css/child/demos/child/index.html, css/child/index.md
Маленький ПР, в котором поменял один из цветов на фирменный и название демки
=> Обновляет демку в «Псевдоклассы группы child»

css/border-width/demos/basic/index.html, css/border-width/demos/different-border/index.html, css/border-width/index.md
Принёс стильных демок
Было:
Стало:
Было2:
Стало2:
https://content-4673.dev.doka.guide/css/border-width/
=> Обновляет демки в `border-width`

recipes/snow/demos/result-no-toggler/index.html, recipes/snow/demos/result/index.html, recipes/snow/index.md
Немного изменила разметку, обновила стиль демки (чекбоксы).
=> Обновляет рецепт Снежинки

recipes/index.md
Короткий фикс с добавлением рецепта в индекс
=> Добавляет рецепт в индекс

docs/demos/style.md
Добавила кнопку с цветом раздела доступности.
=> Обновляет документацию по стилям демок

css/clip/demos/basic/index.html, css/clip/demos/interactive/index.html, css/clip/index.md
Добавил немного фирменного дизайна и сделал вторую демку вертикальной во имя мобилок
Было:
Стало:
Было2:
Стало2:
https://content-4696.dev.doka.guide/css/clip/
=> Обновляет демки в `clip`

a11y/aria-keyshortcuts/demos/button-with-shortcut/index.html, a11y/aria-keyshortcuts/index.md
Добавила демку с легендарной кнопкой. Что ещё приводить в пример, когда рассказываешь про доступность 😅
https://content-4758.dev.doka.guide/a11y/aria-keyshortcuts/
=> Добавляет демку в доку про `aria-keyshortcuts`

a11y/wcag/index.md
Добавила одну актуальную ссылочку.
=> Добавляет ссылку на карту WCAG 2.2

tools/algorithm-complexity/index.md
Заметил несколько опечаток в примерах кода. Исправил их 🙌
=> Исправляет опечатки в примерах кода

.github/workflows/editorconfig.yml, .github/workflows/featured-articles.yml, .github/workflows/frontmatter-lint.yml, .github/workflows/link-checker-all.yml, .github/workflows/maintainer-helper.yml, .github/workflows/pr-checks.yml, .github/workflows/pr-labels.yml, .github/workflows/pr-preview.yml, .github/workflows/product-deploy.yml, .github/workflows/social-cards.yml, .github/workflows/update-dates.yml, .github/workflows/update-index.yml
Версии экшенов GitHub устарели, , пора было обновить, сборка сайта теперь на 20-ой версии Node. Этот пиар связан с [пиаром в платформе](https://github.com/doka-guide/platform/pull/1223), мёржить надо после него.
=> Обновляет экшены

CHANGELOG.md
Оказалось, что формат представления записей не был единым. Починил.
=> Приводит формат представления записей к одному формату

people/alexafcode/index.md
Добавляет alexafcode в people
- [x ] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x ] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)
=> Добавляет alexafcode в people

js/index.md
Добавляет новые доки по JS в разделы Массивы и Объекты.
=> Добавляет новые доки по JS в индекс

a11y/forced-colors/index.md
Были устаревшие сведения о слабой поддержке, исправлено на основе актуальных данных caniuse.com
=> Исправляет сведения о поддержке браузерами

js/index.md
Добавляет новые доки по JS в раздел Массивы.
=> Добавляет новые доки в индекс js

js/promise-allsettled/index.md
Исправляет вывод консоли в примере демонстрирующем работу allSettled().
Пример должен подчеркнуть что массив результатов выполнения промисов, сохраняет порядок оригинального массива, а не порядок выполнения. В существующем варианте ошибка:
```js
const promises = [
new Promise(resolve => setTimeout(() => resolve(1), 3000)),
new Promise((resolve, reject) => setTimeout(() => reject('error'), 2000)),
new Promise(resolve => setTimeout(() => resolve(3), 1000))
]
Promise.allSettled(promises)
.then(([response1, response2, response3]) => {
console.log(response1)
// { status: 'fulfilled', value: 3 }
console.log(response2)
// { status: 'rejected', reason: 'error' }
console.log(response3)
// { status: 'fulfilled', value: 1 }
})
```
response1 вернёт `{ status: 'fulfilled', value: 1 }`
response3 вернёт …
=> Исправляет вывод консоли в результатах примера работы allSettled()

tools/testing-with-jest/index.md
В статье "Пишем первые тесты" есть ссылки на три видео, первая и третья ссылки ведут по одному адресу. Подставила ссылку на нужное видео.
Closes #4690
=> Исправляет ссылку в "Пишем первые тесты"

html/svg-sprite/index.md
=> Корректирует пример для svg-sprite

css/font-size/demos/em-2/index.html, css/font-size/demos/em/index.html, css/font-size/demos/rem/index.html, css/font-size/index.md
Наткнулась на демки в старом дизайне, обновила.
https://doka.guide/css/font-size/ → https://content-5110.dev.doka.guide/css/font-size/
=> Обновляет демки в font-size

new.sh
Исправляет проблему "syntax error near unexpected token `then'".
=> Исправляет new.sh

settings/featured.md
Мы давно не обновляли фичеринг статей. Добавила прикольные новые статьи в запиненые, чуть обновила рандомный список готовых к фичерингу статей. 
@TatianaFokina @HellSquirrel фил фри добавлять свои варианты!
=> Обновляет фичеринг статей на главной

interviews/adaptive-responsible/index.md
Добавляет вопрос из #5169 на платформу.
=> Добавляет новый вопрос для собеседования

recipes/index.md
Добавляет рецепт 'Мгновенная валидация форм' в индекс раздела 'Интерфейс'
=> Добавляет рецепт 'Мгновенная валидация форм' в индекс раздела 'Интерфейс'

css/animation-name/demos/default/index.html, css/animation-name/demos/multiple/index.html, css/animation-name/index.md
Добавляет 2 примера применения этого свойства
Closes [Добавить интерактивный пример в доку про animation-name](https://github.com/doka-guide/content/issues/4318)
=> Добавляет больше интерактивных примеров к animation-name

html/index.md
Добавляет статью 'Что такое семантика?' в индекс раздела html
=> Добавляет статью 'Что такое семантика?' в индекс раздела  html

js/index.md
Добавила доки в существующие разделы и добавила новый.
=> JS: Обновляет индекс раздела

js/set/demos/set-array-difference/index.html
При большом количестве элементов в массиве, который отображался в демке, съезжала форма с инпутом и кнопкой, сделал её центрирование.
=> Поправил демку в статье про `Set`.

css/index.md, recipes/index.md
Хотела ещё в Веб-платформе обновить, но не придумала в какой подраздел засунуть потерявшиеся статьи. Нужна помощь @igsekor и @HellSquirrel
=> Обновляет индексы разделов CSS и Рецепты

js/array-every/practice/windrushfarer.md
В статье про .every в разделе практики во втором примере отсутствует закрывающая скобка у условия if.
=> Добавляет не закрытую скобку в разделе практики

pages/newsletters/index.md
=> Добавляет дайджест за апрель в список

css/image-rendering/index.md
=> Добавляет бэктики в название статьи `image-rendering`

css/scrollbar-width/index.md
Right browser support info
Closes #
=> Обновляет информацию о поддержке `scroll-width`

pages/about/index.md
Меняет старые ссылки на новые — связан с [этим пиаром](https://github.com/doka-guide/platform/pull/1271) в платформе
=> Меняет ссылки

pages/newsletters/index.md
Добавляет очередную рассылку в архив
=> Добавляет рассылку за май в рассылку

js/array-keys/index.md
=> Опечатка в примере кода

js/array-from/index.md
В данном примере document.getElementsByTagName('a') возвращает HTMLCollection, а не NodeList
Closes #
=> Исправляет подзаголовок

recipes/dragndrop-upload/demos/dragndrop-demo/index.html, recipes/dragndrop-upload/index.md
=> Исправляет опечатку в рецепте про Драг-н-дроп

js/event-prevent-default/index.md
Error 
Error in the word setTimeout
=> Исправляет опечатку в доке про `.preventDefault()`

pages/newsletters/index.md
=> Добавляет новую рассылку в архив

pages/newsletters/index.md
=> Добавляет рассылку за октябрь

css/index.md
Разнесла по подразделам статьи, которые были без привязки. Добавила подраздел «Тёмная тема»
=> CSS: обновляет индекс раздела

pages/newsletters/index.md
=> Добавляет рассылку в архив

CODEOWNERS
=> Добавляет себя в CODEOWNERS

CODEOWNERS
=> Обновляет CODEOWNERS

js/number-is-nan/demos/index/index.html, js/number-is-nan/index.md
* Меняет сетку
* Добавляет адаптив
* Упрощает html
* Предпочитает rem / логические свойства
* сортирует css свойства
* Меняет input хандлер без изменения core логики  
* Добавляет transitions
* Меняет вымышленную валюту
* Использует Intl для формата числа
Closes #5570
=> Обновляет «Калькулятор скидки» — `Number.isNaN()`

.github/workflows/product-deploy.yml
В этом пиаре удаляется этап подготовки карточек для социальных сетей, поскольку мы переходим на другие рельсы.
=> Убирает этап генерации карточек для социальных сетей

html/flow/demos/absolute/index.html, html/flow/demos/float/index.html, html/flow/demos/inline/index.html, html/flow/demos/margin-collapse-empty/index.html, html/flow/demos/margin-collapse-siblings/index.html, html/flow/demos/normal-animated/index.html, html/flow/demos/normal-width/index.html, html/flow/demos/normal/index.html
Добавляет минимальный адаптив к демкам в [статье](https://doka.guide/html/flow/) "Поток документа"
Closes #5583
=> Добавляет адаптив к демкам (#5583)

pages/newsletters/index.md
=> Добавляет декабрьский дайджест в архив

pages/newsletters/index.md
=> Добавляет рассылку за январь

people/akhmadullin/index.md, people/dimameh/index.md, people/egorlem/index.md, people/harutoyume/index.md, people/kirpinev/index.md, people/vladislav149/index.md
Добавляет значки за первый контрибьюшен тем, кому сразу не досталось
=> Добавляет значки за первый контрибьюшен

README.md
Удаляет лейблы отсутствующих экшнов
=> Удаляет лейблы отсутствующих экшнов

pages/newsletters/index.md
=> Добавляет рассылку за март в архив

CHANGELOG.md
Возврат к корням, так сказать.
=> Обновляет CHANGELOG.md руками

html/style/index.md
исправила опечатку в слове кулинарный
Closes #5739
=> Исправила опечатку в слове

js/destructuring-assignment/index.md
Fix: correct variable name 'second' to 'restNumbers' in the article destructuring-assignment
=> Исправляет пример в доке 'Деструктуризация'

people/disi/index.md
Не заметила, что у @Disinterpreter нет авторской папки. Если ты хочешь указать своё имя, добавить какую-то ещё инфу про себя, то поправь файл из этого пиара.
=> Добавляет нового контрибьютера

CHANGELOG.md
Пока всё сломано, я притворяюсь работающим флоу.
=> Добавляет ченджлог за июль 2025

a11y/a11y-html/index.md
=> Добавляет ссылки в статью про доступность и HTML

css/index.md, html/index.md
Добавляет доки в подходящие разделы:
- css/print-color-adjust -> Стили для печати
- html/images-paste-methods -> Картинки
=> Добавляет новые доки в индексы разделов
