doka-guide/content

js/doka/array-filter/index.md

тег контрибуторов был заведен дважды строкой, а надо один раз массивом, YAML-файл при сборке ломался. Поправлено

Правит контрибуторов

---

CODEOWNERS

Оунерство — это такой механизм, который помогает **точечно** настроить права на критические части кода, у которых на самом деле есть оунеры. В таком случае их призовут в ПР и без их участия этот код не смёржится.
Важное слово здесь «точечно». У нас сейчас есть три оунера:
- Алёна — html, css
- Коля — js, tools
- Оля — docs, ридми
Без их участия такие пулреквесты не надо мёржить, они обидятся.
Что я сделал:
1. Убрал первую строчку
Она пыталась сделать всех оунерами всех файлов. Что это бы значило на практике, если бы она работала: при каждом ПР всех участников списка ставило бы ревьюерами. Это можно сделать в другом синтексисе, но кажется это плохая идея звать вообще всех.
2. Убрал явного оунера папки people
Сейчас, если приходит простой ПР для папки people, то Гитхаб очень строго говорит …

Правит оунеров

---

.github/workflows/surge-preview.yml

Попробовал превью для контента выстроить с помощью [Surge](https://surge.sh/).
Для этого существует уже готовый [экшн](https://github.com/marketplace/actions/surge-pr-preview). Получается, что можно не платить, и выглядит вроде бы интересно. Работает только при наличии ключа для SURGE_TOKEN в секретах репозитория, который нужно сгенерировать по [инструкции](https://surge.sh/help/integrating-with-circleci), предварительно скачав [npm пакет surge](https://surge.sh/help/getting-started-with-surge).
Что думаете?

Добавляет превью для контента на Surge

---

.github/workflows/editorconfig.yml
.github/workflows/yaspeller-all.yml
.github/workflows/yaspeller-pr.yml

@pepelsbey @nlopin @furtivite, предлагаю разбить проверку правописания на два трэка: при пуше в ветку `main` и при PR. Что думаете?
Внёс условие для `Yaspeller`, чтобы он не проверял файлы, если они не *.md и не *.html. Попробую запихнуть такие и другие файлы, отладить, а потом удалить всё лишнее. Должно сработать. Это проблема, которая описана в #751.

Разбивает проверку правописания на два экшна

---

js/doka/includes/demos/includes.html
js/doka/includes/practice/nlopin.md

- Убирает обёртку `article__code`
- Упрощает демку последовательно на тегах
- Убирает борьбу с автозаполнением `internal-autofill-selected`
- Делает демку на форме, чтобы можно было отправить её энтером
- Использует удобный атрибут `hidden` вместо классов, чтобы прятать
- Немного форматирует код в совете
Сделал в рамках #776

Рефакторит демку для includes

---

.github/workflows/editorconfig.yml
.github/workflows/yaspeller-pr.yml

В экшне исправлена ошибка, которая афектила:
1. https://github.com/Y-Doka/content/pull/717
2. https://github.com/Y-Doka/content/pull/733
3. https://github.com/Y-Doka/content/pull/819
Решение проблемы [найдено](https://github.com/jitterbit/get-changed-files/pull/25) и уже воплощено в [форке](https://github.com/Ana06/get-changed-files/releases/tag/v1.2) прежнего [экшна](https://github.com/jitterbit/get-changed-files). В PR заменил пока на форк. Из плюсов: теперь можем ещё и фильтровать файлы из пиара, если будет нужно.

Исправляет ошибки в тестах

---

CODEOWNERS

Кажется, когда раставляли CODEOWNERS забыли, что решение о добавлении слова в словарь принимает редактор. Добавляет @tachisis к овнерам словаря.

Добавляет редактора в словарь

---

.github/scripts/update-index.js
.github/workflows/updated-at-field.yml

Fix: #1122
Похоже, что основная проблема была в том, что _action/chekout_ скачивает только последний коммит, но для работы команды `git diff-tree` нужны как минимум два, чтобы построить список файлов.
Плюс добавил в игнор изменения файлов индексов статей, которые будут в _css/index.md_, _html/index.md_ и др.

Правит action для обновления data-файлов

---

tools/nodejs-tooling/index.md

Сейчас есть две статьи с заголовком «Что такое Node.js?». Этот пул реквест правит заголовок одной из них

Изменяет заголовок статьи о тулинге на Node.js

---

css/float/index.md

Правит мету, фиксит сломанную ссылку на статью

Правит мету в статье про float

---

css/sticky/index.md

Правит мету, фиксит сломанную ссылку на статью

Правит мету в статье про Липкое позиционирование

---

js/element-outerhtml/index.md

Кажется немного перепутали :) Плюс записывает ник строчными, как и название папки [в people](https://github.com/doka-guide/content/tree/main/people).

Правит название статьи

---

.github/scripts/frontmatter.js
.github/workflows/frontmatter-lint.yml
tools/network/index.md
tools/xml/index.md

При проверке меты возникала ошибка, связанная с некорректной командой для bas-скрипта. При выполнении команды отдельно в консоле проблемы не возникало. Теперь всё работает корректно, хотя код и стал менее читаемый.

Исправляет команду для проверки нужных папок

---

.github/workflows/surge-preview.yml

Работа экшена для сборки была некорректной для форков. В процессе решения возникшей проблемы решил отвязать [внешний экшен](https://github.com/doka-guide/surge-preview) для превью и осуществить публикацию на Surge с помощью консольной утилиты.

Преобразует экшен для превью

---

js/async-in-js/index.md

Пока мы не подготовили видео, которое показывает, как функции «путешествуют» между стеком, очередью задач и Web API, я подумал, что будет хорошо показать это как минимум в виде таблиц.
Немного заодно укоротил текст и уточнил отсылки к `console.log`, чтобы было понятно, какой именно лог выводится.
(Кажется, это лучше, чем просто блоки текста. Возможно, даже когда появится видео, стоит оставить эти таблицы как транскрипт.)

Использует таблицы для большей наглядности

---

css/stroke/demos/pattern/index.html
css/stroke/index.md

https://doka.guide/css/stroke
| До | После |
| -- | ----- |
|  ![Слишком большой отступ у демо снизу](https://user-images.githubusercontent.com/30597878/139338106-fd1b417a-a024-4ed0-9252-9f69e8469fba.png)| ![Демо с нормальным размером](https://user-images.githubusercontent.com/30597878/139338095-f0cb9b62-95ba-469e-a4c3-848c1f11b038.png) |

Исправление высоты демо в css/stroke

---

css/stacking-context/index.md

В строке 109 говорится про z-index и position: relative. Но в примере кода, указан только position: relative

Добавил z-index про который говорится в тексте, но нет в примере

---

.github/workflows/sort-dictionary.yml

[Судя по документации](https://github.com/actions/setup-node#matrix-testing), в `matrix` нужно всегда передавать массив

Исправляет падающий сортировщик словаря

---

tools/bundlers/index.md

Если подключать скрипт в шапку, то к моменту выполнения ещё негде будет менять текст. Перенёс скрипт в конец.
Заодно поправил название пакета, во втором Парселе это просто `parcel`.
p.s. Репорт не мой. Давали ссылку для доп.чтения, а прилетел фидбек. Но исправленный пример проверил: запустил в Парселе, всё заработало.

Исправит ошибку в примере на странице "Системы сборки"

---

html/var/demos/basic/index.html

Если ширина браузера < 598px, то контент внутри iframe режет головку

Исправляет контент внутри iframe

---

.github/workflows/link-checker-all.yml

На текущий момент при проверке битых ссылок в собранном сайте отсутствуют исключения в виде локалхоста ([пример](https://github.com/doka-guide/content/runs/4330856706?check_suite_focus=true#step:5:70)).
Данный ПР добавляет в исключения `localhost`, `127.0.0.1`, а также `codepen.io` - последний я взял из экшена рядом, который проверяет маркдаун файлы.
Исправляет doka-guide/platform#769
UPD:
Совместно с автором ruzickap/action-my-broken-link-checker/pull/52 исправили экшен проверки битых ссылок и теперь он корректно обрабатывает тег `<picture />` с множественными `srcSet` - из-за чего вывод не тонет в потоке нерелевантного мусора.
Дополнительно я предлагаю убрать полностью экшен `JustinBeckwith/linkinator-action@v1` - во-первых он в текущей конфигурации просто напросто не работает. …

Улучшает проверку битых ссылок

---

html/strong/demos/view/index.html
html/strong/index.md

Проходил мимо статьи, демка показалась очень яркой на тёмной теме, добавил цвета и поправил высоту, чтобы полоса прокрутки не появлялась. 
Было:
Стало:

Перекрашивает демку и немного правит высоту

---

.github/workflows/link-checker-all.yml

Решает doka-guide/platform/issues/769
Как я уже писал в исходном ишью - у нас экшен проверки ссылок запускает два экшена:
1.  `JustinBeckwith/linkinator-action@v1` - он проверяет ссылки в переданных markdown файлах. Фактически же - [не работает](https://github.com/doka-guide/content/runs/4330856706?check_suite_focus=true#step:4:14).
2. `ruzickap/action-my-broken-link-checker` - проверяет настоящий сайт Доки. Сейчас его починили и он отлично работает, закрывая все потребности проверки битых ссылок.
Я спрашивал и в ПР и в ишью касательно удаления `JustinBeckwith/linkinator-action@v1` - никто не высказался против, правда никто и не подтвердил что нужно :)
Поэтому создал этот ПР, можем обсудить это здесь, а по итогу закрыть оригинальный ишью.

Удаляет лишний экшен для проверки ссылок

---

css/selection/index.md

По [спецификации](https://drafts.csswg.org/css-pseudo-4/#highlight-styling) `::selection` не умеет стилизовать cursor, caret-color и outline, но при этом умеет стилизовать текст в SVG.
На всякий случай проверил локально, умеет ли в браузерах мимо спецификации — не получилось изменить cursor и caret-color (каретка в принципе не видна, когда делается выделение), а outline — это история про box, который при выделении тоже сбрасывается. Смог сымитировать выделение и focus на элементе через принудительное выставление статуса в DevTools — всё равно внутри выделения цвет не меняется.
Также уточнил про версию Firefox, потому что современный Firefox в вендорном префиксе не нуждается.

Дополняет про ::selection

---

js/array-filter/index.md

nums[i] - пример с ошибкой - 177 строка. Пушим переменную которой нет.

nums[i] - пример с ошибкой

---

CHANGELOG.md

Мне понадобился список январских статей, но чейнджлога не нашёл. Сделал сам, надеюсь, всё правильно. 
Мы же дату считаем датой мержа?

Добавляет статьи за январь в ченжлог

---

.github/scripts/search-index.js
.github/workflows/update-index.yml

Вместо разделения на отдельные сущности - параграфы, заголовки, изображения и пр. - создаётся линейный список блочных элементов. Благодаря этому можно взять определённое количество таких элементов, в  которых есть совпадения, и вывести в результаты поиска.
Относится к [этому PR для сайта](https://github.com/doka-guide/platform/pull/866).

Перестраивает поисковый индекс для использования возможностей Algolia для подсветки результатов

---

js/typecasting/index.md

При поиске "приведение типов" сейчас на первом месте выскакивает статья про `Map`, но если добавить ключевое слово, то по идее должна будет показываться нужная статья про преобразование типов

Добавляет ключевое слово в статью про преобразование типов

---

settings/featured.md

Оставила три статьи, которые были в самом низу запиненых, на втором экране. Есть вероятность, что многие их не видели. Остальные перенесла в ready

Переносит зафичеренные статьи из pined в ready

---

css/grid-guide/index.md
css/grid/index.md

[Fix #2701](https://github.com/doka-guide/content/issues/2701)

Переименовывает селекторы .item в .container для статьи 'css/grid'

---

js/design-patterns-creational/index.md

Переименовывает переменную в примере статьи «Порождающие паттерны проектирования»

---

css/scroll-behavior/index.md

В Safari 15.4 [появилась поддержка scroll-behavior](https://caniuse.com/?search=scroll-behavior)

Убирает плашку о поддержке в Safari

---

tools/gulp/index.md

В статье про Gulp есть две якорные ссылки, которые заканчиваются слешем. 
Исправляет.
P.S.: Возможно, нам нужно пересмотреть чек-лист, видимо, он вводит в заблуждение и люди ставят слеш там, где это не требуется.

Правит якорные ссылки

---

css/outline-width/index.md

В пылу редактуры забыли вписать @Granondo автором доки про `outline-width` и убрать тег плейсхолдера

Поправляет автора в доке про `outline-width`

---

pages/about/index.md

1. Добавляет ссылки на персональные страницы для членов редакции.
2. Добавляет ссылку [на страницу контрибьюторов](https://www.doka.guide/people/)
Это первая итерация, но начать можно с неё. Также стоит внимательно посмотреть на предложение со ссылкой на страницу контрибьюторов.
Плюс мне кажется странным раздел «Особая благодарность» в том виде, в котором он есть сейчас. Надо развернуть, что люди помогали нам на запуске. Плюс, возможно, перенести ссылку на замечательных контрибьюторов именно туда.

Добавляет ссылки на людей из редакции и на страницу с контрибьюторами

---

js/design-patterns-structural/index.md

if (machine.getTemperature() <= 90) { 
machine.turnOffHeater();
}
По контексту нужно выключить подогрев воды когда температура будет выше или равна 90. Но с текущим условием подогрев будет выключаться сразу же, так как скорее всего температура воды при включении будет ниже 90.

Правит условие подогрева воды в кофемашине

---

.github/frontmatter.json

В Доке теперь есть возможность добавлять похожие или смежные по смыслу статьи, чтобы помочь читателю расширить кругозор или хорошо провести время. PR призван добавить это поле в список разрешённых для линтера меты.

Добавляет новое поле related в список разрешённых

---

js/element-textcontent/index.md

Неправильная ссылка на статью про `innerHTML`.

Фиксит ссылку на связанную статью

---

a11y/aria-placeholder/index.md

Добавляет плейсхолдер для доки про aria-placeholder

---

a11y/aria-expanded/index.md

Добавляет плейсхолдер для aria-expanded

---

a11y/aria-readonly/index.md

Добавляет плейсхолдер для доки про aria-readonly

---

js/getelementsbyclassname/index.md

В 40-й строке по моему закралась ошибка, вместо document должен быть divEl.
Closes #

Правит опечатку в коде доки `.getElementsByClassName()`

---

a11y/aria-owns/index.md

Добавила пробелы внутрь `<aside>`.

Улучшает плейсхолдер для доки про `aria-owns`

---

a11y/aria-disabled/index.md

Перелинковала с другими доками.

Добавляет ссылки к плейсхолдеру про `aria-disabled`

---

a11y/aria-expanded/index.md

Перелинковала с другими доками и заменила одну связанную статью.

Добавляет ссылки в плейсхолдер доки про `aria-expanded`

---

a11y/role-button/index.md

Перелинковала с другими доками.

Добавляет ссылки к плейсхолдеру доки про роль `button`

---

a11y/role-alert/index.md

Добавляет ссылку в плейсхолдер статьи про роль `alert`

---

.github/workflows/pr-checks.yml

Теперь проверка форматирования не будет проверять удалённые файлы и сыпать в [логи](https://github.com/doka-guide/content/actions/runs/3082774153/jobs/4982885863) красным:
```
Проверка для .github/ISSUE_TEMPLATE/1_error_report.md
Could not get the ContentType of file: .github/ISSUE_TEMPLATE/1_error_report.md
stat .github/ISSUE_TEMPLATE/1_error_report.md: no such file or directory
```
Хотя проверки от этого не проваливались, но логи теперь будут без страшных красных надписей. Да и во всём 
остальном экшене и так использовался только `$steps.files.outputs.added_modified` и только в этом случае почему-то был `$steps.files.outputs.all`.

Улучшает PR чекер

---

js/events/demos/this/index.html

Ошибка: в мобильной версии у первого элемента отсутствовал отступ
Исправлено путем замены margin-left на flex-разметку
<details>
<summary>Было</summary>
</details>
<details>
<summary>Стало</summary>
</details>

Правит отступы

---

.github/scripts/description-helper.js

Раньше скрипт зачем-то удалял последнюю статью из массива, каждый раз, когда находил статью с дескрипшеном:
```js
const hasDescription = // some code
const item = // some code
if (hasDescription) {
issueLists[chapter].pop(item)
} else {
issueLists[chapter].push(item)
}
```
Поведение странное, как минимум потому что методу `pop()` не нужно никаких аргументов. Он всегда удаляет и возвращает последний элемент.
Из-за этого бага в соответствующих ищью на данный момент недостаёт 29 статей про CSS и 2 статьи про HTML.

Исправляет скрипт для дескрипшенов

---

settings/featured.md

Запинила статью «Что такое доступность» и докинула в общую подборку ещё две: `aria-labelledby` и skip link.

Добавляет статьи из a11y в фичеринг

---

.github/labeler.yml

Ставим лейбл раздела при изменении любого файла в разделе. Так мы точнее будем размечать разделы. 
До этого мы смотрели только на md-файлы и поэтому многие пул реквесты приходилось размечать руками. Например, изменение картинки или демки

Ослабляет правила по назначению лейблов разделов

---

settings/featured.md

Докинула пару статей в запиненые, чтобы рядом с зелёной карточкой доступности точно не вставала другая зелёная карточка из инструментов. Плюс добавила несколько статей из доступности и из рецептов в список вселенского рандома. 
@HellSquirrel @TatianaFokina если вы хотите запинить или добавить в рандом какие-то статьи — самое время =)

Формирует новый фичеринг

---

.github/pull_request_template.md

Поправил примеры для относительных ссылок в PR шаблоне: добавил пример с картинкой и добавил указание пути до папки демки вместо пути до файла.

Правит примеры относительных ссылок

---

js/cookie/index.md

В методе `getCookie` нет необходимости на каждой итерации делать поверхностное копирование объекта. Из-за этого значительно повышается сложность алгоритма.

Уменьшает вычислительную сложность в примере получения cookie

---

pages/about/index.md

Исправил ссылку на профиль @TatianaFokina в разделе [Кто мы](https://doka.guide/about/#kto-my) на странице [О проекте](https://doka.guide/about/)

Исправляет ссылку на профиль редактора доки

---

js/element-dataset/index.md

Исправлена опечатка в примере использования.
Было неверно указано число, которое использовалось в js-коде и которое выводилось по итогу в html.

Исправляет опечатку в доке `.dataset`

---

a11y/role-navigation/index.md

Исправила небольшую ошибку в названии роли в примере с кодом.

Исправляет код в доке `navigation`

---

.github/workflows/pr-preview.yml
recipes/self-hosted-preview/index.md

Согласно [этой новости в блоге GitHub](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) от 11 октября 2022 команда `set-output` помечена устаревшей. Данный PR заменяет ее на рекомендуемый синтаксис во всех местах репозитория, где она встречалась, как в статье про экшены, так и в одном из экшенов.

Заменяет устаревшую команду set-output в GitHub Actions

---

docs/demos/style.md

Добавляет в шаблон в стайлгайде по демкам свойство `color-scheme: dark;`, как [предлагал cergmin](https://github.com/doka-guide/content/issues/2303#:~:text=%D0%A1%D1%82%D0%BE%D0%B8%D1%82%20%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%20%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%B0%D0%B2%D0%BB%D0%B8%D0%B2%D0%B0%D1%82%D1%8C%20color%2Dscheme%3A%20dark%3B%2C%20%D0%B5%D1%81%D0%BB%D0%B8%20%D1%84%D0%BE%D0%BD%20%D1%82%D1%91%D0%BC%D0%BD%D1%8B%D0%B9%2C%20%D1%87%D1%82%D0%BE%D0%B1%D1%8B%20%D0%B5%D1%81%D0%BB%D0%B8%20%D0%B2%D0%B4%D1%80%D1%83%D0%B3%20%D0%BF%D0%BE%D1%8F%D0%B2%D0%B8%D0%BB%D1%81%D1%8F%20%D1%81%D0%BA%D1%80%D0%BE%D0%BB%D0%BB%D0%B1%D0%B0%D1%80%2C%20%D1%82%D0%BE%20%D0%BE%D0%BD%20%D1%82%D0%BE%D0%B6%D0%B5%20%D0%B1%D1%8B%D0%BB%20%D1%82%D1%91%D0%BC%D0%BD%D1%8B%D0%BC.).

Добавляет в шаблон в стайлгайде по демкам свойство `color-scheme: dark;`

---

a11y/aria-labelledby/index.md

Дополнила доку важным небольшим уточнением.

Добавляет небольшое уточнение в доку про `aria-labelledby`

---

css/grid-guide/index.md
css/place-items/index.md

Исправление синтаксиса:
place-items: <'align-items'> <'justify-items'>;
Значения должны разделяться пробелом, а не слэшем.
Исправление синтаксиса place-items.
https://developer.mozilla.org/en-US/docs/Web/CSS/place-items

Исправляет ошибку в написании значений для `place-items`

---

js/element/index.md

В строке `const element = document.getElementsByTagName('h1')[0]` в конце добавляется `[0]`. Таким образом берется конкретный элемент. Без этого исправления код выдает ошибку.

Исправляет небольшую неточность в `Element`

---

js/array-map/demos/index/index.html

В демо статьи js/array-map объявлены функции:
_function transformToSquare(num)_ и _function transformToCube(num)_
Далее они используются в качестве аргументов в:
_products.map(transformToSquare**s**)_ - изменено на _products.map(transformToSquare)_;
_products.map(transformToCube**s**)_ - изменено на _products.map(transformToCube)_.

Исправлена опечатка в статье .map()

---

css/grid-guide/index.md

- Удаляет бесполезные комментарии.
- Добавляет упоминание `align-self` в `align-items`.
- Удаляет лишний пробел в примере кода.

Исправляет опечатки в `Гайд по grid`

---

css/css-counters/index.md

В статье "Счётчики в CSS" в примере кода опечатка в свойстве counter-reset, поправил её.

Исправляет опечатку в статье "Счётчики в CSS"

---

.github/labeler.yml

Поменялось название раздела «Инструмента». Нужно поменять лейбелер.

Исправляет название лейбла

---

css/where/demos/basic/index.html
css/where/demos/specificity-battle/index.html
css/where/index.md

1. Поправил тег в секции `code` которая появляется после нажатия на кнопку в футере. Код в секции `code` теперь соответствует тому что применяется после нажатия на кнопку в футере
2. Поменял именование на более говорящее `Footer` => `ColorOverride`

Исправляет секцию `code` в демо для :where()

---

a11y/index.md
a11y/role-generic/index.md

Плейсхолдер доки про роль `generic`.

Добавляет плейсхолдер для `generic`

---

a11y/aria-orientation/index.md
a11y/index.md

Ещё один плесхолдер для ARIA-атрибута, который много где упоминается и ещё будет упомянут.

Добавляет плейсхолдер для `aria-orientation`

---

a11y/index.md
a11y/role-menuitemradio/index.md

Плейсхолдер, связанный с другим про `menu`.

Добавляет плейсхолдер для `menuitemradio`

---

a11y/index.md
a11y/role-menuitemcheckbox/index.md

Плейсхолдер, связанный с другим про `menu`.

Добавляет плейсхолдер для `menuitemcheckbox`

---

css/grid-guide/practice/meded90.md
people/meded90/index.md

Кстати, попыталась тут же поправить партнёрскую ссылку тут https://doka.guide/css/grid-guide/#baldin-kirill-sovetuet внизу совета, но гит не показывает никаких изменений. @igsekor можешь, пожалуйста, глянуть, почему не произошла трансформация? Может из-за игнорирования имени?

Исправляет путь до фото контрибьютора

---

css/attribute-selector/demos/cite-bkg/index.html
css/attribute-selector/demos/link-icon/index.html
css/attribute-selector/index.md
css/attribute-selector/practice/ezhkov.md

Заадаптивил демки и поменял ссылки в совете на доковские. Да, лучше вообще не использовать настоящие ссылки, но это лучше, чем те ссылки, которые были, ведь они были сломанными
https://content-4647.dev.doka.guide/css/attribute-selector/

Обновляет демки в «Селектор по атрибуту»

---

css/border-block/demos/border-block-basic/index.html
css/border-block/demos/border-block-language-change/index.html
css/border-block/demos/border-inline/index.html
css/border-block/demos/border-language-change/index.html
css/border-block/demos/border-top-bottom/index.html
css/border-block/index.md
css/border-inline/demos/border-block/index.html
css/border-inline/demos/border-inline-basic/index.html
css/border-inline/demos/border-inline-language-change/index.html
css/border-inline/demos/border-language-change/index.html
css/border-inline/demos/border-left-right/index.html

Маленький прчик, чтобы убрать скролл + добавил `text-align: center;`, чтобы на маленьких экранах текст оставался по середине 👉👈

Обновляет демки в `border-block`, `border-inline`

---

css/caret-color/demos/form/index.html
css/caret-color/demos/paint-the-caret/index.html
css/caret-color/demos/rainbow-input/index.html
css/caret-color/index.md
css/caret-color/practice/mishamad.md

Немного заредизайнил, убрал лишнее: плейсхолдеры в одной из демок (они полностью дублировали лейблы), автофокус в другой (он всё равно не работал в ифрейме). Немного почистил сниппеты от лишнего кода
Было:
Стало:
Было2:
Стало2:
Было3:
Стало3:
https://content-4676.dev.doka.guide/css/caret-color/

Обновляет демки в `caret-color`

---

html/embed/demos/embed-pdf/index.html
html/embed/index.md
html/object/demos/show-pdf/index.html
html/object/index.md

Поменяла высоту фреймов и добавила недостающие стили. Так что внешне ничего особо не поменялось. Там и так всё хорошо. Ещё добавила ссылку на другую доку и отформатировала и обновила пример кода в `<object>`.
https://doka.guide/html/object/ → https://content-4744.dev.doka.guide/html/object/
https://doka.guide/html/embed/ → https://content-4744.dev.doka.guide/html/embed/

Слегка причёсывает демки в `<embed>` и `<object>`

---

css/will-change/practice/madey-kv.md

В разделе `На практике` используется невалидный пример кода. События `animationEnd` не существует, но существует событие `animationend` ([подробнее](https://developer.mozilla.org/en-US/docs/Web/API/Element/animationend_event)).
Однако по контексту раздела больше подходит событие `transitionend`, потому что в примерах выше  [key frames](https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes) до этого не появлялись.
Изменения не затрагивают чек-лист

Исправляет ошибку в `На практике` для `will-change`

---

html/disabled/demos/base/images/arrow-down.svg
html/disabled/demos/base/index.html
html/disabled/index.md

Добавила для демки фирменный стиль и немного рассказала про аналог атрибута в ARIA.
https://doka.guide/html/disabled/ → https://content-4749.dev.doka.guide/html/disabled/

Причёсывает демки и дополняет доку «Атрибут `disabled`»

---

html/multiple/demos/basic/index.html
html/multiple/demos/multiple-input-email/index.html
html/multiple/demos/multiple-input-files/index.html
html/multiple/index.md

Сделала демки «фирменными» и добавила немного инфы про аналог в ARIA.
https://doka.guide/html/multiple/ → https://content-4750.dev.doka.guide/html/multiple/

Обновляет демки в «Атрибут `multiple`»

---

js/element-removeeventlistener/practice/windrushfarer.md

Исправляет неправильное название функции в .removeEventListener() для обработчика события клавиатуры в разделе "На практике"   
Closes #4732

Исправляет неправильное название функции в .removeEventListener()

---

css/active/index.md

Исправляет опечатку в разделе "Составной селектор в состоянии :active". В примере написано ":focus" вместо ":active"

Исправляет опечатку в разделе "Составной селектор в состоянии :active"

---

html/autocomplete/index.md

* Добавляет autocomplete="off", так как он по умолчанию всегда "on"
В статье написано "Создадим форму, в которую пользователь будет сам вводить имя, а при заполнении поля e-mail сможет выбрать адрес почты из предложенных браузером вариантов:" после чего ставиться autocomplete="on" у поля e-mail, но ведь у имени тоже по умолчанию будет autocomplete="on", то есть тоже "сможет выбрать из предложенных браузером вариантов"

Правит статью autocomplete

---

a11y/live-region/demos/toast-notification/index.html

В статье ["Что такое изменяющаяся область"](https://doka.guide/a11y/live-region/) в [демке c уведомлениями](https://doka.guide/a11y/live-region/demos/toast-notification/) сам блок с уведомлением виден скринридерам, из-за чего они читают кнопку "Закрыть".

Скрывает от скринридеров невидимый визуально блок с уведомлением

---

a11y/aria-describedby/demos/field-with-hint/index.html
a11y/aria-describedby/index.md
a11y/aria-description/demos/button-with-description/index.html
a11y/aria-description/index.md
a11y/aria-errormessage/demos/field-with-aria-errormessage/index.html
a11y/aria-errormessage/index.md
a11y/aria-hidden/demos/button-with-icon-font/index.html
a11y/aria-hidden/index.md
a11y/aria-labelledby/demos/figure-with-aria-labelledby/index.html
a11y/aria-labelledby/index.md
a11y/role-contentinfo/demos/footer-with-contentinfo/index.html
a11y/role-contentinfo/index.md
a11y/role-switch/demos/button-with-switch-role/index.html
a11y/role-switch/index.md

Предпоследняя пачка демок, в которых в основном добавила недостающее начертание для бесконечных кнопок и `color-scheme`.
https://doka.guide/a11y/aria-errormessage/ → https://content-4983.dev.doka.guide/a11y/aria-errormessage/
https://doka.guide/a11y/aria-hidden/ → https://content-4983.dev.doka.guide/a11y/aria-hidden/ 
https://doka.guide/a11y/aria-description/ → https://content-4983.dev.doka.guide/a11y/aria-description/ 
https://doka.guide/a11y/aria-describedby/ → https://content-4983.dev.doka.guide/a11y/aria-describedby/
https://doka.guide/a11y/aria-labelledby/ → https://content-4983.dev.doka.guide/a11y/aria-labelledby/
https://doka.guide/a11y/role-switch/ → https://content-4983.dev.doka.guide/a11y/role-switch/ 
https://doka.guide/a11y/role-contentinfo/ → …

Доступность: Причёсывает демки

---

js/index.md

Добавляет ссылку на доку по array.push() в раздел Массивы.

Добавляет array.push() к списку методов массива в index

---

new.sh

В текущей версии `new.sh` используется логика получения github-логина с использованием запроса:
```bash
LOGIN=$(echo $(curl -s https://api.github.com/search/users\?q\=$(echo $(git config --get user.email)) | jsonValue login))
```
Этот код имеет недостатки по двум причинам:
1. Запрос ничего не даст, в случае если в настройках github установлена опция `Keep my email addresses private` и в репозитории используется email вида `USER@users.noreply.github.com`. (Мне кажется, это довольно распространённая практика).
Вот что происходит в моём случае:
```bash
$ curl -s https://api.github.com/search/users\?q\=9317613+vitya-ne@users.noreply.github.com
{
"total_count": 0,
"incomplete_results": false,
"items": [
]
}
```
2. Зачем вообще делать какой-то запрос на github, когда мы можем использовать …

Упрощает диалог  в new.sh

---

html/svg-sprite/demos/sprite/index.html

В материале про svg-спрайты есть демо (`html/svg-sprite/demos/sprite`), в котором не применялись стили для иконки facebook'а (`.sprite-demo__social-icon_facebook`)

Исправляет стили для иконки facebook'а в демо

---

recipes/lazy-load-with-preview/index.md

Если у изображения битый src или его не удалось загрузить по иным причинам, то мы получим заблюренный alt текст, чтобы этого избежать нужно добавить дополнительный хендлер onerror

Дорабатывает код рецепта «Ленивая загрузка картинок»

---

a11y/role-switch/index.md

Дополнила новой инфой про нативное решение для переключателя + исправила ошиМбочки.

Дополняет доку про роль `switch`

---

js/deal-with-forms/index.md

Для статьи https://doka.guide/js/deal-with-forms/?utm_source=social в примере переместил использование функции filter перед функцией map.
Мне кажется, что так будет логичнее по 2м причинам.
1) В примерах до и после filter стоит перед map, а в этом примере он стоит ниже map и немного сбивает, начинаешь задумываться, а почему его вдруг переместили после map :)
2) С точки зрения работы логики, мы сначала через filter уберем пустой элемент для button (где name: ' '), а затем пройдемся map-ом. Иначе элемент button с пустым name будет учавствовать в обходе циклов 2 раза (один для map, а потом для filter). 
В примере ниже filter расположен выше map, и я думаю, что для текущего примера (по которому правка), просто случайно поменяли местами.

Исправляет порядок применения функций filter, map в примере

---

js/index.md

Добавляет доку .closest() в раздел Element

Добавляет доку .closest() в индекс js

---

js/if-else/practice/saharok.md

Исправляет ссылку на описание оператора nullish coalescing.

Исправляет ссылку nullish coalescing

---

.github/scripts/update-dates.js

Чтобы дата наконец появилась в материалах раздела «Доступность» и «Рецепты».

Добавляет a11y и рецепты в скрипт обновления даты

---

people/kozlovtseva/index.md
recipes/validation/demos/final-form/index.html
recipes/validation/index.md

Улучшения формы в статье Мгновенная валидация форм:
- валидация поля при вводе, отображение ошибок при анфокусе и по событию submit, сброс валидации на поле с фокусом
- чекбокс вынесен отдельно от общего списка инпутов, тк событие blur на нем отрабатывает в момент повторного клика, а мы этого не хотим. Для чекбокса отдельно добавлено событие 'change' ('input', 'blur', 'focus' ему не нужны)
- исправлен символ пробела в регулярке
- добавлен метод пост
- отредактировано описание функций в соответствии с правками
номер ишью - #5273 
- [✓] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [✓] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, …

Улучшения формы в статье Мгновенная валидация форм

---

css/transform/demos/playground/index.html

[Демка из статьи про `transform`](https://doka.guide/css/transform/demos/playground/)
Попробуйте с клавиатуры ввести значение translateX. Не получится, только ползунком. Хотя остальные функции можно и так и так изменять.
Там используется библиотека dat.GUI. Я попробовал убрать метод `.listen()` — всё работает как надо.
Аналогичная проблема описана [здесь](https://github.com/dataarts/dat.gui/issues/206) и [здесь](https://github.com/NVlabs/WebFPSci/issues/3)

Чинит демку

---

.github/scripts/update-changelog.js
.github/scripts/update-changelog.sh
CHANGELOG.md

Забавно видеть коммиты от имени Дока Дога :) Забыл переключить :)

Решает проблемы #5456

---

js/generators/index.md

При вызове `.next()` у генератора, `done: true` вернется после того, как все `yield` закончатся

Исправляет ошибку вывода при вызове генератора

---

tools/index.md

Добавляет статью про [Deno](https://doka.guide/tools/deno/) в секцию `Сборка проекта`, чтобы Node.js чувствовал конкуренцию даже тут.
Возможно Deno и Node,js достойны отдельного раздела, но пока его нет, помоему лучше, чтобы они  были рядом.

Обновляет индекс раздела "Веб-платформа"

---

html/head/index.md

Предлагаю добавить `<template>`  и `<noscript>` в список тегов, которые можно использовать внутри `<head>`. Тогда в доке будет полный список допустимых тегов.

Добавлены допустимые теги внутри <head>

---

recipes/snow/demos/result-no-toggler/index.html
recipes/snow/demos/result/index.html
recipes/snow/index.md

Стоит добавить `aria-hidden="true"` в код рецепта, так как без него пользователь скринридера будет слушать все 90 звёздочек 😭

Устанавливает `aria-hidden="true"` для снежинок

---

css/scrollbar-gutter/index.md

Заметил, что в [статье про scrollbar-gutter](https://doka.guide/css/scrollbar-gutter/) говорится о том, что это свойство недоступно в сафари.
Но в сафари 18.2 [добавили поддержку](https://caniuse.com/mdn-css_properties_scrollbar-gutter), поэтому этот абзац больше не актуален.

Убирает предупреждение о неработающем scrollbar-gutter в Safari

---

tools/design-patterns-behaviorial/index.md

Исправляет название интерфейса для поля `routeFinder` класса `Context` на `RouteStrategy`.

Исправляет ошибку в статье 'Поведенческие паттерны проектирования'

---

.github/scripts/update-changelog.js

Сейчас при записи изменений в файлик с ченджлогом между пунктами списков добавляются пробелы. Попыталась исправить эту мелочь.

Убирает пустые строки в списках из CHANGELOG.md

---

css/appearance/index.md
css/aspect-ratio/index.md
css/backdrop/index.md
css/background-attachment/index.md
css/clip-path/index.md
css/color-scheme/index.md
css/column-span/index.md
css/conic-gradient/index.md
css/layer/index.md
css/repeating-conic-gradient/index.md
html/dialog/index.md

Добавляет конфигурацию baseline к докам:
- css/appearance
- css/aspect-ratio
- css/backdrop
- css/background-attachment
- css/clip-path
- css/color-scheme
- css/column-span
- css/conic-gradient
- css/layer
- css/repeating-conic-gradient
- html/dialog
Эти фичи перешли в разряд широко поддерживаемых за период 2023-2024
Источник: https://web-platform-dx.github.io/web-features-explorer/widely-available/
Тестировал локально с версией web-features 2.22.0

Добавляет конфигурацию baseline для css и html фич ('широко поддерживаемые' за 2023-2024)

---

css/caret-color/index.md

Тег `p` должен быть внутри формы.

Исправляет пример в доке `caret-color`

---

js/index.md

Добавляет доку про метод `Set.isDisjointFrom()` в раздел JS

Добавляет `isDisjointFrom()` в индекс JS

---

a11y/prefers-contrast/index.md
css/accent-color/index.md
css/light-dark/index.md
css/marker/index.md
css/scrollbar-color/index.md
css/starting-style/index.md
html/inert/index.md
js/element-touch/index.md

- accent-color
- ::marker
- scrollbar-color
- @starting-style
- inert
- touch
- light-dark
- prefers-contrast
Источник: https://web-platform-dx.github.io/web-features-explorer/one-missing-engine/

Добавляет информацию baseline для фич с неполной поддержкой

---

css/disabled-enabled/index.md

Заменил отступ перед свойством в 2 таба, на отступ в 1 таб, как во всех других примерах.
- [+] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [+] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [+] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

Корректирует пример в доке `:disabled, :enabled `

---

js/fetch/practice/windrushfarer.md

🔴 В текущем варинате в консоли отображаются неправильные значения:
Исправляет вычисление и показ полученной части файла:
- значение полученной части вычисляем как процент:
```js
received += value.length / contentLength * 100
```
- округление применяем только для показа значения:
```js
const result = Math.floor(received)
if (result < 100) {
console.log(`Получено ${result}%`)
}
```
Closes #5759

Исправляет вычисление полученной части в примере использования fetch

---

js/event-prevent-default/practice/g-milevski.md

Исправляет опечатку в  разделе 'На практике'
Closes #5819

Исправляет опечатку в доке 'preventDefault()'

---

css/index.md
html/index.md

Добавляет:
- CSS-доки в раздел 'Работа с текстом'
- `text-box-edge`
- `text-box-trim`
- HTML-доку в раздел 'Глобальные атрибуты':
- `autofocus`

Добавляет новые доки в разделы СSS и HTML

---

js/urlsearchparams/index.md

Исправляет описание колбэк-функции метода `forEach()` экземпляра `URLSearchParams`.
Closes #5855

Исправляет описание метода `URLSearchParams: forEach()`
